import {mkdtemp,mkdir,readFile,readdir,rm,writeFile} from "node:fs/promises";
import {existsSync} from "node:fs";
import {tmpdir} from "node:os";
import {delimiter,join} from "node:path";
import {spawn} from "node:child_process";
export type JavaDiagnostic={severity:"error"|"warning";message:string};
export type JavaCompilation={language:"java";representation:"JVM bytecode";jdkVersion:string;primaryClass:string;bytecodeIR:string;classes:Record<string,Buffer>;jar:{fileName:string;bytes:Buffer};diagnostics:JavaDiagnostic[];metrics:{classCount:number;classBytes:number;jarBytes:number}};
export class JavaFrontendError extends Error{constructor(readonly diagnostics:JavaDiagnostic[]){super(diagnostics.map(d=>`${d.severity}: ${d.message}`).join("\n"));this.name="JavaFrontendError";}}
export async function compileJava(source:string):Promise<JavaCompilation>{if(!source.trim())throw new JavaFrontendError([{severity:"error",message:"Java source is empty"}]);const classMatch=source.match(/\bpublic\s+(?:final\s+)?class\s+([A-Za-z_$][\w$]*)/)??source.match(/\bclass\s+([A-Za-z_$][\w$]*)/);if(!classMatch)throw new JavaFrontendError([{severity:"error",message:"A top-level class declaration is required"}]);const primaryClass=classMatch[1]!,jdk=await locateJdk(),workspace=await mkdtemp(join(tmpdir(),"c-optiforge-java-")),classesDir=join(workspace,"classes"),sourcePath=join(workspace,`${primaryClass}.java`),jarPath=join(workspace,`${primaryClass}.jar`);try{await mkdir(classesDir);await writeFile(sourcePath,source,"utf8");const compiled=await command(jdk.javac,["-encoding","UTF-8","-g:none","-Xlint:all","-d",classesDir,sourcePath]);if(compiled.code!==0)throw new JavaFrontendError([{severity:"error",message:compiled.stderr||compiled.stdout}]);const files=(await readdir(classesDir,{recursive:true})).filter(name=>String(name).endsWith(".class")).map(String),classes:Record<string,Buffer>={};for(const name of files)classes[name.replaceAll("\\","/")]=await readFile(join(classesDir,name));const inspected=await command(jdk.javap,["-classpath",classesDir,"-c","-p",primaryClass]);if(inspected.code!==0)throw new Error(`javap failed: ${inspected.stderr}`);const hasMain=/\bstatic\s+void\s+main\s*\(/.test(source),jarArgs=["--create","--file",jarPath,...(hasMain?["--main-class",primaryClass]:[]),"-C",classesDir,"."];const packed=await command(jdk.jar,jarArgs);if(packed.code!==0)throw new Error(`jar packaging failed: ${packed.stderr}`);const jarBytes=await readFile(jarPath),version=await command(jdk.javac,["-version"]),classBytes=Object.values(classes).reduce((sum,value)=>sum+value.byteLength,0);return{language:"java",representation:"JVM bytecode",jdkVersion:(version.stderr||version.stdout).trim(),primaryClass,bytecodeIR:inspected.stdout,classes,jar:{fileName:`${primaryClass}.jar`,bytes:jarBytes},diagnostics:compiled.stderr.trim()?[{severity:"warning",message:compiled.stderr.trim()}]:[],metrics:{classCount:files.length,classBytes,jarBytes:jarBytes.byteLength}};}finally{await rm(workspace,{recursive:true,force:true});}}
async function locateJdk(){const homes=[process.env.COPTIFORGE_JDK_HOME,process.env.JAVA_HOME,"C:\\Program Files\\Java\\jdk-21.0.12.1"].filter(Boolean) as string[];if(process.platform==="win32"&&existsSync("C:\\Program Files\\Java")){for(const name of await readdir("C:\\Program Files\\Java"))if(name.startsWith("jdk-"))homes.push(join("C:\\Program Files\\Java",name));}for(const home of homes){const suffix=process.platform==="win32"?".exe":"",bin=join(home,"bin"),javac=join(bin,`javac${suffix}`);if(existsSync(javac))return{javac,javap:join(bin,`javap${suffix}`),jar:join(bin,`jar${suffix}`),java:join(bin,`java${suffix}`)};}const pathDirs=(process.env.PATH??"").split(delimiter);for(const bin of pathDirs){const suffix=process.platform==="win32"?".exe":"",javac=join(bin,`javac${suffix}`);if(existsSync(javac))return{javac,javap:join(bin,`javap${suffix}`),jar:join(bin,`jar${suffix}`),java:join(bin,`java${suffix}`)};}throw new Error("JDK compiler not found. Set COPTIFORGE_JDK_HOME or JAVA_HOME to a JDK 21 installation.");}
export async function javaRuntimePath(){return(await locateJdk()).java;}
function command(executable:string,args:string[]){return new Promise<{code:number;stdout:string;stderr:string}>((resolve,reject)=>{const child=spawn(executable,args,{windowsHide:true}),stdout:Buffer[]=[],stderr:Buffer[]=[];child.stdout.on("data",c=>stdout.push(c));child.stderr.on("data",c=>stderr.push(c));child.on("error",reject);child.on("close",code=>resolve({code:code??-1,stdout:Buffer.concat(stdout).toString("utf8"),stderr:Buffer.concat(stderr).toString("utf8")}));});}
