import mysql, { type Pool, type PoolConnection, type ResultSetHeader, type RowDataPacket } from "mysql2/promise";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { CapabilityProfile, NodeStatus, ResourceSnapshot, TaskStatus, WorkPayload } from "@c-optiforge/contracts";
import type {CIntermediateRepresentation} from "@c-optiforge/compiler-c";

export type DatabaseConfig={host:string;port:number;name:string;user:string;password:string};

export class Store {
  private constructor(readonly pool:Pool){}
  static async connect(config:DatabaseConfig){const pool=mysql.createPool({host:config.host,port:config.port,database:config.name,user:config.user,password:config.password,waitForConnections:true,connectionLimit:10,queueLimit:0,timezone:"Z",decimalNumbers:true});const store=new Store(pool);await store.migrate();return store;}
  async close(){await this.pool.end();}
  private async migrate(){const statements=[
    `CREATE TABLE IF NOT EXISTS sessions (id VARCHAR(64) PRIMARY KEY,status ENUM('ACTIVE','CLOSED','EXPIRED') NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32) NOT NULL,INDEX idx_sessions_status(status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS invitations (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,status ENUM('PENDING','ACCEPTED','DECLINED','REDEEMED','EXPIRED') NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32) NOT NULL,accepted_at VARCHAR(32),enrollment_hash CHAR(64) UNIQUE,enrollment_expires_at VARCHAR(32),redeemed_at VARCHAR(32),CONSTRAINT fk_invitation_session FOREIGN KEY(session_id) REFERENCES sessions(id),INDEX idx_invitations_session(session_id,status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS nodes (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,invitation_id VARCHAR(64) NOT NULL UNIQUE,role ENUM('WORKER') NOT NULL,status ENUM('REGISTERING','ONLINE','AVAILABLE','BUSY','UNAVAILABLE','OFFLINE') NOT NULL,profile_json JSON NOT NULL,resource_json JSON,worker_token_hash CHAR(64) NOT NULL UNIQUE,registered_at VARCHAR(32) NOT NULL,last_heartbeat VARCHAR(32) NOT NULL,disconnected_at VARCHAR(32),current_task_id VARCHAR(64),CONSTRAINT fk_node_session FOREIGN KEY(session_id) REFERENCES sessions(id),CONSTRAINT fk_node_invitation FOREIGN KEY(invitation_id) REFERENCES invitations(id),INDEX idx_nodes_session_status(session_id,status),INDEX idx_nodes_heartbeat(last_heartbeat)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS tasks (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,kind VARCHAR(64) NOT NULL,payload_json JSON NOT NULL,required_capability VARCHAR(64) NOT NULL,status ENUM('QUEUED','ASSIGNED','RUNNING','COMPLETED','FAILED','REQUEUED') NOT NULL,assigned_node_id VARCHAR(64),attempt INT NOT NULL DEFAULT 0,created_at VARCHAR(32) NOT NULL,started_at VARCHAR(32),completed_at VARCHAR(32),error TEXT,CONSTRAINT fk_task_session FOREIGN KEY(session_id) REFERENCES sessions(id),CONSTRAINT fk_task_node FOREIGN KEY(assigned_node_id) REFERENCES nodes(id),INDEX idx_tasks_status(status,created_at)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS results (id VARCHAR(64) PRIMARY KEY,task_id VARCHAR(64) NOT NULL,node_id VARCHAR(64) NOT NULL,attempt INT NOT NULL,result_json JSON NOT NULL,execution_time_ms DOUBLE NOT NULL,resource_json JSON NOT NULL,created_at VARCHAR(32) NOT NULL,CONSTRAINT fk_result_task FOREIGN KEY(task_id) REFERENCES tasks(id),CONSTRAINT fk_result_node FOREIGN KEY(node_id) REFERENCES nodes(id),UNIQUE KEY uq_result_attempt(task_id,attempt)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS task_attempts (task_id VARCHAR(64) NOT NULL,attempt INT NOT NULL,node_id VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL,scheduler_score DOUBLE NOT NULL,scheduler_explanation TEXT NOT NULL,assigned_at VARCHAR(32) NOT NULL,started_at VARCHAR(32),completed_at VARCHAR(32),error TEXT,PRIMARY KEY(task_id,attempt),CONSTRAINT fk_attempt_task FOREIGN KEY(task_id) REFERENCES tasks(id),CONSTRAINT fk_attempt_node FOREIGN KEY(node_id) REFERENCES nodes(id),INDEX idx_attempt_node_status(node_id,status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS optimization_batches (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,language VARCHAR(16) NOT NULL,status ENUM('DISTRIBUTING','COMPLETED','FAILED') NOT NULL,original_ir_json JSON NOT NULL,selected_ir_json JSON,evaluation_json JSON,created_at VARCHAR(32) NOT NULL,completed_at VARCHAR(32),CONSTRAINT fk_batch_session FOREIGN KEY(session_id) REFERENCES sessions(id),INDEX idx_batch_status(status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS optimization_batch_tasks (batch_id VARCHAR(64) NOT NULL,task_id VARCHAR(64) NOT NULL,function_name VARCHAR(200) NOT NULL,PRIMARY KEY(batch_id,task_id),CONSTRAINT fk_batch_task_batch FOREIGN KEY(batch_id) REFERENCES optimization_batches(id),CONSTRAINT fk_batch_task_task FOREIGN KEY(task_id) REFERENCES tasks(id),UNIQUE KEY uq_batch_task(task_id)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS compilation_jobs (id VARCHAR(64) PRIMARY KEY,language ENUM('c','python','java') NOT NULL,source_name VARCHAR(255) NOT NULL,source_text MEDIUMTEXT NOT NULL,status ENUM('SUBMITTED','DISTRIBUTING','CODE_GENERATING','COMPLETED','FAILED') NOT NULL,stage VARCHAR(64) NOT NULL,batch_id VARCHAR(64),error TEXT,metrics_json JSON,created_at VARCHAR(32) NOT NULL,completed_at VARCHAR(32),CONSTRAINT fk_job_batch FOREIGN KEY(batch_id) REFERENCES optimization_batches(id),INDEX idx_jobs_status_created(status,created_at)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS artifacts (id VARCHAR(64) PRIMARY KEY,job_id VARCHAR(64) NOT NULL UNIQUE,file_name VARCHAR(255) NOT NULL,media_type VARCHAR(150) NOT NULL,content LONGBLOB NOT NULL,size_bytes BIGINT NOT NULL,created_at VARCHAR(32) NOT NULL,CONSTRAINT fk_artifact_job FOREIGN KEY(job_id) REFERENCES compilation_jobs(id)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS users (id VARCHAR(64) PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(320) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('ADMIN','USER') NOT NULL,status ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE',created_at VARCHAR(32) NOT NULL,updated_at VARCHAR(32) NOT NULL,INDEX idx_users_email(email)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS auth_sessions (token_hash CHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32) NOT NULL,revoked_at VARCHAR(32),ip_hash CHAR(64),user_agent_hash CHAR(64),CONSTRAINT fk_auth_session_user FOREIGN KEY(user_id) REFERENCES users(id),INDEX idx_auth_sessions_user(user_id,revoked_at),INDEX idx_auth_sessions_expiry(expires_at)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS password_reset_tokens (token_hash CHAR(64) PRIMARY KEY,user_id VARCHAR(64) NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32) NOT NULL,used_at VARCHAR(32),CONSTRAINT fk_reset_user FOREIGN KEY(user_id) REFERENCES users(id),INDEX idx_reset_user(user_id,used_at),INDEX idx_reset_expiry(expires_at)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS distributed_networks (id VARCHAR(64) PRIMARY KEY,public_id VARCHAR(64) NOT NULL UNIQUE,join_token_hash CHAR(64) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,description VARCHAR(1000) NOT NULL DEFAULT '',status ENUM('ACTIVE','DISABLED','EXPIRED') NOT NULL,created_by VARCHAR(64) NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32),max_nodes INT NOT NULL DEFAULT 50,configuration_json JSON NOT NULL,CONSTRAINT fk_network_creator FOREIGN KEY(created_by) REFERENCES users(id),INDEX idx_network_status(status,created_at),INDEX idx_network_join(join_token_hash)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS network_enrollments (id VARCHAR(64) PRIMARY KEY,network_id VARCHAR(64) NOT NULL,device_identity_hash CHAR(64),consent_status ENUM('ACCEPTED','REVOKED') NOT NULL,status ENUM('PENDING','ACTIVE','REVOKED','EXPIRED') NOT NULL,worker_type ENUM('BROWSER','NATIVE') NOT NULL,credential_hash CHAR(64) NOT NULL UNIQUE,created_at VARCHAR(32) NOT NULL,updated_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32),revoked_at VARCHAR(32),CONSTRAINT fk_enrollment_network FOREIGN KEY(network_id) REFERENCES distributed_networks(id),INDEX idx_enrollment_network(network_id,status)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS audit_events (id VARCHAR(64) PRIMARY KEY,actor_type ENUM('ADMIN','USER','WORKER','SYSTEM') NOT NULL,actor_id VARCHAR(64),event_type VARCHAR(100) NOT NULL,target_type VARCHAR(64),target_id VARCHAR(64),metadata_json JSON NOT NULL,created_at VARCHAR(32) NOT NULL,INDEX idx_audit_created(created_at),INDEX idx_audit_actor(actor_type,actor_id),INDEX idx_audit_event(event_type)) ENGINE=InnoDB`
  ];for(const sql of statements)await this.pool.execute(sql);await this.ensureColumn("tasks","scheduler_score","DOUBLE NULL");await this.ensureColumn("tasks","scheduler_explanation","TEXT NULL");await this.ensureColumn("tasks","job_id","VARCHAR(64) NULL");await this.ensureColumn("tasks","network_id","VARCHAR(64) NULL");await this.ensureColumn("tasks","user_id","VARCHAR(64) NULL");await this.ensureColumn("nodes","network_id","VARCHAR(64) NULL");await this.ensureColumn("nodes","enrollment_id","VARCHAR(64) NULL");await this.ensureColumn("nodes","worker_type","VARCHAR(16) NOT NULL DEFAULT 'NATIVE'");await this.ensureColumn("nodes","revoked_at","VARCHAR(32) NULL");await this.ensureColumn("compilation_jobs","user_id","VARCHAR(64) NULL");await this.ensureColumn("compilation_jobs","network_id","VARCHAR(64) NULL");await this.ensureColumn("optimization_batches","network_id","VARCHAR(64) NULL");await this.pool.execute("ALTER TABLE nodes MODIFY session_id VARCHAR(64) NULL, MODIFY invitation_id VARCHAR(64) NULL");await this.pool.execute("ALTER TABLE tasks MODIFY session_id VARCHAR(64) NULL");await this.pool.execute("ALTER TABLE optimization_batches MODIFY session_id VARCHAR(64) NULL");await this.ensureIndex("nodes","idx_nodes_network_status","network_id,status,last_heartbeat");await this.ensureIndex("tasks","idx_tasks_network_status","network_id,status,created_at");await this.ensureIndex("compilation_jobs","idx_jobs_user_created","user_id,created_at");await this.ensureIndex("compilation_jobs","idx_jobs_network_status","network_id,status,created_at");await this.ensureForeignKey("nodes","fk_nodes_network","network_id","distributed_networks","id");await this.ensureForeignKey("nodes","fk_nodes_enrollment","enrollment_id","network_enrollments","id");await this.ensureForeignKey("tasks","fk_tasks_network","network_id","distributed_networks","id");await this.ensureForeignKey("tasks","fk_tasks_user","user_id","users","id");await this.ensureForeignKey("compilation_jobs","fk_jobs_network","network_id","distributed_networks","id");await this.ensureForeignKey("compilation_jobs","fk_jobs_user","user_id","users","id");}
  private async ensureColumn(table:string,column:string,definition:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[table,column]);if(!rows.length)await this.pool.execute(`ALTER TABLE \`${table}\` ADD COLUMN \`${column}\` ${definition}`);}
  private async ensureIndex(table:string,name:string,columns:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?",[table,name]);if(!rows.length)await this.pool.execute(`ALTER TABLE \`${table}\` ADD INDEX \`${name}\` (${columns.split(",").map(column=>`\`${column}\``).join(",")})`);}
  private async ensureForeignKey(table:string,name:string,column:string,parentTable:string,parentColumn:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME=?",[name]);if(!rows.length)await this.pool.execute(`ALTER TABLE \`${table}\` ADD CONSTRAINT \`${name}\` FOREIGN KEY (\`${column}\`) REFERENCES \`${parentTable}\`(\`${parentColumn}\`)`);}
  now(){return new Date().toISOString();} hash(token:string){return createHash("sha256").update(token).digest("hex");} token(){return randomBytes(32).toString("base64url");} id(prefix:string){return `${prefix}-${randomUUID()}`;}
  private async transaction<T>(work:(connection:PoolConnection)=>Promise<T>){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const result=await work(connection);await connection.commit();return result;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}

  async heartbeat(nodeId:string,resources:ResourceSnapshot){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT status FROM nodes WHERE id=?",[nodeId]);const row=rows[0] as {status:NodeStatus}|undefined;if(!row||row.status==="OFFLINE")return false;const status=row.status==="ONLINE"||row.status==="UNAVAILABLE"?"AVAILABLE":row.status;await this.pool.execute("UPDATE nodes SET status=?,resource_json=?,last_heartbeat=?,disconnected_at=NULL WHERE id=?",[status,JSON.stringify(resources),this.now(),nodeId]);return true;}
  async markDisconnected(nodeId:string){await this.pool.execute("UPDATE nodes SET status='OFFLINE',disconnected_at=? WHERE id=? AND status!='OFFLINE'",[this.now(),nodeId]);}
  async recoverStaleNodes(staleBefore:string,offlineBefore:string){return this.transaction(async connection=>{const[rows]=await connection.execute<RowDataPacket[]>("SELECT id,status,last_heartbeat lastHeartbeat,current_task_id currentTaskId FROM nodes WHERE last_heartbeat<? AND status!='OFFLINE' AND revoked_at IS NULL FOR UPDATE",[staleBefore]);const recovered: Array<{nodeId:string;taskId:string|null;status:"UNAVAILABLE"|"OFFLINE"}> = [];for(const row of rows){const nodeId=String(row.id),taskId=row.currentTaskId?String(row.currentTaskId):null,status=Date.parse(String(row.lastHeartbeat))<Date.parse(offlineBefore)?"OFFLINE":"UNAVAILABLE",timestamp=this.now(),reason=`Worker heartbeat lost; node marked ${status}`;if(taskId){const[taskRows]=await connection.execute<RowDataPacket[]>("SELECT attempt FROM tasks WHERE id=? FOR UPDATE",[taskId]);const attempt=Number(taskRows[0]?.attempt??0);await connection.execute("UPDATE task_attempts SET status='INTERRUPTED',completed_at=?,error=? WHERE task_id=? AND attempt=? AND status IN ('ASSIGNED','RUNNING')",[timestamp,reason,taskId,attempt]);await connection.execute("UPDATE tasks SET status=IF(attempt>=3,'FAILED','REQUEUED'),error=?,assigned_node_id=NULL,completed_at=IF(attempt>=3,?,completed_at) WHERE id=? AND status IN ('ASSIGNED','RUNNING')",[reason,timestamp,taskId]);}await connection.execute("UPDATE nodes SET status=?,current_task_id=NULL,disconnected_at=CASE WHEN ?='OFFLINE' THEN ? ELSE disconnected_at END WHERE id=?",[status,status,timestamp,nodeId]);recovered.push({nodeId,taskId,status});}return recovered;});}
  async createJobWorkTask(jobId:string,networkId:string,kind:"PYTHON_COMPILE"|"JAVA_COMPILE",payload:WorkPayload,capability:"python"|"java"){const id=this.id("TASK"),createdAt=this.now();await this.pool.execute("INSERT INTO tasks(id,session_id,network_id,kind,payload_json,required_capability,status,created_at,job_id) VALUES(?,NULL,?,?,?,?, 'QUEUED',?,?)",[id,networkId,kind,JSON.stringify(payload),capability,createdAt,jobId]);return{id,networkId,kind,payload,status:"QUEUED" as TaskStatus,attempt:0};}
  async getCompilationJobForTask(taskId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT job_id jobId FROM tasks WHERE id=?",[taskId]);return rows[0]?.jobId?this.getCompilationJob(String(rows[0].jobId)):undefined;}
  async createCOptimizationBatch(networkId:string,ir:CIntermediateRepresentation){return this.transaction(async connection=>{const batchId=this.id("BATCH"),createdAt=this.now(),tasks: Array<{taskId:string;functionName:string;status:"QUEUED"}> = [];await connection.execute("INSERT INTO optimization_batches(id,session_id,network_id,language,status,original_ir_json,created_at) VALUES(?,NULL,?,'c','DISTRIBUTING',?,?)",[batchId,networkId,JSON.stringify(ir),createdAt]);for(const fn of ir.functions){const taskId=this.id("TASK"),payload={operation:"c_optimize_ir" as const,function:fn};await connection.execute("INSERT INTO tasks(id,session_id,network_id,kind,payload_json,required_capability,status,created_at) VALUES(?,NULL,?,'C_OPTIMIZE_IR',?,'ir','QUEUED',?)",[taskId,networkId,JSON.stringify(payload),createdAt]);await connection.execute("INSERT INTO optimization_batch_tasks(batch_id,task_id,function_name) VALUES(?,?,?)",[batchId,taskId,fn.name]);tasks.push({taskId,functionName:fn.name,status:"QUEUED"});}return{batchId,irKind:ir.kind,irVersion:ir.version,tasks};});}
  async getCOptimizationBatchForTask(taskId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT batch_id batchId FROM optimization_batch_tasks WHERE task_id=?",[taskId]);return rows[0]?this.getCOptimizationBatch(String(rows[0].batchId)):undefined;}
  async getCOptimizationBatch(batchId:string){const[[batchRows],[taskRows]]=await Promise.all([this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,status,original_ir_json originalIrJson,selected_ir_json selectedIrJson,evaluation_json evaluationJson,created_at createdAt,completed_at completedAt FROM optimization_batches WHERE id=?",[batchId]),this.pool.execute<RowDataPacket[]>(`SELECT bt.task_id taskId,bt.function_name functionName,t.status,t.assigned_node_id nodeId,t.attempt,r.result_json resultJson,r.execution_time_ms executionTimeMs FROM optimization_batch_tasks bt JOIN tasks t ON t.id=bt.task_id LEFT JOIN results r ON r.task_id=t.id AND r.attempt=t.attempt WHERE bt.batch_id=? ORDER BY bt.function_name`,[batchId])]);const row=batchRows[0];if(!row)return undefined;return{id:String(row.id),sessionId:String(row.sessionId),status:String(row.status),originalIR:this.parseJson<CIntermediateRepresentation>(row.originalIrJson),selectedIR:row.selectedIrJson?this.parseJson<CIntermediateRepresentation>(row.selectedIrJson):null,evaluation:row.evaluationJson?this.parseJson(row.evaluationJson):null,createdAt:String(row.createdAt),completedAt:row.completedAt?String(row.completedAt):null,tasks:taskRows.map(task=>({taskId:String(task.taskId),functionName:String(task.functionName),status:String(task.status),nodeId:task.nodeId?String(task.nodeId):null,attempt:Number(task.attempt),executionTimeMs:task.executionTimeMs===null?null:Number(task.executionTimeMs),result:task.resultJson?this.parseJson<any>(task.resultJson):null}))};}
  async completeCOptimizationBatch(batchId:string,selectedIR:CIntermediateRepresentation,evaluation:unknown){const[result]=await this.pool.execute<ResultSetHeader>("UPDATE optimization_batches SET status='COMPLETED',selected_ir_json=?,evaluation_json=?,completed_at=? WHERE id=? AND status='DISTRIBUTING'",[JSON.stringify(selectedIR),JSON.stringify(evaluation),this.now(),batchId]);return result.affectedRows===1;}
  async createCompilationJob(userId:string,networkId:string,language:"c"|"python"|"java",sourceName:string,source:string){const id=this.id("JOB"),createdAt=this.now();await this.pool.execute("INSERT INTO compilation_jobs(id,user_id,network_id,language,source_name,source_text,status,stage,created_at) VALUES(?,?,?,?,?,?,'SUBMITTED','VALIDATING',?)",[id,userId,networkId,language,sourceName,source,createdAt]);return{id,userId,networkId,language,sourceName,status:"SUBMITTED",stage:"VALIDATING",createdAt};}
  async attachJobBatch(jobId:string,batchId:string){await this.pool.execute("UPDATE compilation_jobs SET status='DISTRIBUTING',stage='DISTRIBUTED_OPTIMIZATION',batch_id=? WHERE id=?",[batchId,jobId]);}
  async setJobStage(jobId:string,status:string,stage:string){await this.pool.execute("UPDATE compilation_jobs SET status=?,stage=? WHERE id=?",[status,stage,jobId]);}
  async completeCompilationJob(jobId:string,artifact:{fileName:string;mediaType:string;bytes:Buffer},metrics:unknown){await this.transaction(async connection=>{const artifactId=this.id("ARTIFACT"),now=this.now();await connection.execute("INSERT INTO artifacts(id,job_id,file_name,media_type,content,size_bytes,created_at) VALUES(?,?,?,?,?,?,?)",[artifactId,jobId,artifact.fileName,artifact.mediaType,artifact.bytes,artifact.bytes.byteLength,now]);await connection.execute("UPDATE compilation_jobs SET status='COMPLETED',stage='COMPLETED',metrics_json=?,completed_at=?,error=NULL WHERE id=?",[JSON.stringify(metrics),now,jobId]);});}
  async failCompilationJob(jobId:string,error:string){await this.pool.execute("UPDATE compilation_jobs SET status='FAILED',stage='FAILED',error=?,completed_at=? WHERE id=?",[error,this.now(),jobId]);}
  async getCompilationJob(jobId:string){const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT j.id,j.user_id userId,j.network_id networkId,j.language,j.source_name sourceName,j.status,j.stage,j.batch_id batchId,j.error,j.metrics_json metricsJson,j.created_at createdAt,j.completed_at completedAt,a.id artifactId,a.file_name fileName,a.media_type mediaType,a.size_bytes sizeBytes FROM compilation_jobs j LEFT JOIN artifacts a ON a.job_id=j.id WHERE j.id=?`,[jobId]);const row=rows[0];return row?{id:String(row.id),userId:row.userId?String(row.userId):null,networkId:row.networkId?String(row.networkId):null,language:String(row.language),sourceName:String(row.sourceName),status:String(row.status),stage:String(row.stage),batchId:row.batchId?String(row.batchId):null,error:row.error?String(row.error):null,metrics:row.metricsJson?this.parseJson(row.metricsJson):null,createdAt:String(row.createdAt),completedAt:row.completedAt?String(row.completedAt):null,artifact:row.artifactId?{id:String(row.artifactId),fileName:String(row.fileName),mediaType:String(row.mediaType),sizeBytes:Number(row.sizeBytes)}:null}:undefined;}
  async getCompilationJobByBatch(batchId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id FROM compilation_jobs WHERE batch_id=?",[batchId]);return rows[0]?this.getCompilationJob(String(rows[0].id)):undefined;}
  async getArtifact(artifactId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,job_id jobId,file_name fileName,media_type mediaType,content,size_bytes sizeBytes FROM artifacts WHERE id=?",[artifactId]);const row=rows[0];return row?{id:String(row.id),jobId:String(row.jobId),fileName:String(row.fileName),mediaType:String(row.mediaType),content:row.content as Buffer,sizeBytes:Number(row.sizeBytes)}:undefined;}
  async pendingTasks(){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,network_id networkId,kind,payload_json payloadJson,required_capability requiredCapability,status,attempt FROM tasks WHERE network_id IS NOT NULL AND status IN ('QUEUED','REQUEUED') ORDER BY created_at");return rows.map(row=>({id:String(row.id),networkId:String(row.networkId),kind:String(row.kind) as "TEST_COMPUTE"|"C_OPTIMIZE_IR"|"PYTHON_COMPILE"|"JAVA_COMPILE",payload:this.parseJson<WorkPayload>(row.payloadJson),requiredCapability:String(row.requiredCapability) as "base"|"ir"|"c"|"python"|"java",status:row.status as TaskStatus,attempt:Number(row.attempt)}));}
  async getTask(taskId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,kind,payload_json payloadJson,status,assigned_node_id assignedNodeId,attempt FROM tasks WHERE id=?",[taskId]);const row=rows[0];return row?{...row,payload:this.parseJson(row.payloadJson),payloadJson:undefined}:undefined;}
  async availableNodes(networkId:string){const[[rows],[historyRows]]=await Promise.all([this.pool.execute<RowDataPacket[]>("SELECT id,status,profile_json profileJson,resource_json resourceJson,last_heartbeat lastHeartbeat FROM nodes WHERE network_id=? AND revoked_at IS NULL AND status='AVAILABLE' AND current_task_id IS NULL",[networkId]),this.pool.execute<RowDataPacket[]>(`SELECT a.node_id nodeId,t.required_capability capability,COUNT(*) sampleCount,AVG(r.execution_time_ms) averageExecutionTimeMs,AVG(a.status='COMPLETED') successRate FROM task_attempts a JOIN tasks t ON t.id=a.task_id LEFT JOIN results r ON r.task_id=a.task_id AND r.attempt=a.attempt WHERE t.network_id=? AND a.status IN ('COMPLETED','FAILED','TIMED_OUT','INTERRUPTED') GROUP BY a.node_id,t.required_capability`,[networkId])]);const history=new Map<string,Record<string,unknown>>();for(const item of historyRows){if(item.averageExecutionTimeMs===null)continue;const record=history.get(String(item.nodeId))??{};record[String(item.capability)]={sampleCount:Number(item.sampleCount),averageExecutionTimeMs:Number(item.averageExecutionTimeMs),successRate:Number(item.successRate)};history.set(String(item.nodeId),record);}return rows.map(row=>({id:String(row.id),status:String(row.status),profile:this.parseJson<CapabilityProfile>(row.profileJson),resources:row.resourceJson?this.parseJson<ResourceSnapshot>(row.resourceJson):null,lastHeartbeat:String(row.lastHeartbeat),historicalPerformance:history.get(String(row.id))??{}}));}
  async assignTask(taskId:string,nodeId:string,score:number,explanation:string){return this.transaction(async connection=>{const[rows]=await connection.execute<RowDataPacket[]>("SELECT status,attempt,network_id networkId FROM tasks WHERE id=? FOR UPDATE",[taskId]);const task=rows[0] as {status:TaskStatus;attempt:number;networkId:string}|undefined;if(!task||!["QUEUED","REQUEUED"].includes(task.status))throw new Error("Task is not assignable");const attempt=Number(task.attempt)+1,assignedAt=this.now();const[nodeChanged]=await connection.execute<ResultSetHeader>("UPDATE nodes SET status='BUSY',current_task_id=? WHERE id=? AND network_id=? AND revoked_at IS NULL AND status='AVAILABLE' AND current_task_id IS NULL",[taskId,nodeId,task.networkId]);if(nodeChanged.affectedRows!==1)throw new Error("Node is unavailable or belongs to another network");await connection.execute("UPDATE tasks SET status='ASSIGNED',assigned_node_id=?,attempt=?,scheduler_score=?,scheduler_explanation=?,error=NULL WHERE id=?",[nodeId,attempt,score,explanation,taskId]);await connection.execute("INSERT INTO task_attempts(task_id,attempt,node_id,status,scheduler_score,scheduler_explanation,assigned_at) VALUES(?,?,?,'ASSIGNED',?,?,?)",[taskId,attempt,nodeId,score,explanation,assignedAt]);return attempt;});}
  async setTaskRunning(taskId:string,nodeId:string,attempt:number){return this.transaction(async connection=>{const now=this.now();const[result]=await connection.execute<ResultSetHeader>("UPDATE tasks SET status='RUNNING',started_at=? WHERE id=? AND assigned_node_id=? AND attempt=? AND status='ASSIGNED'",[now,taskId,nodeId,attempt]);if(result.affectedRows===1)await connection.execute("UPDATE task_attempts SET status='RUNNING',started_at=? WHERE task_id=? AND attempt=? AND node_id=? AND status='ASSIGNED'",[now,taskId,attempt,nodeId]);return result.affectedRows===1;});}
  async completeTask(taskId:string,nodeId:string,attempt:number,result:unknown,executionTimeMs:number,resources:ResourceSnapshot){await this.transaction(async connection=>{const now=this.now();const[changed]=await connection.execute<ResultSetHeader>("UPDATE tasks SET status='COMPLETED',completed_at=? WHERE id=? AND assigned_node_id=? AND attempt=? AND status='RUNNING'",[now,taskId,nodeId,attempt]);if(changed.affectedRows!==1)throw new Error("Stale or invalid task result");await connection.execute("UPDATE task_attempts SET status='COMPLETED',completed_at=? WHERE task_id=? AND attempt=? AND node_id=? AND status='RUNNING'",[now,taskId,attempt,nodeId]);await connection.execute("INSERT INTO results(id,task_id,node_id,attempt,result_json,execution_time_ms,resource_json,created_at) VALUES(?,?,?,?,?,?,?,?)",[this.id("RESULT"),taskId,nodeId,attempt,JSON.stringify(result),executionTimeMs,JSON.stringify(resources),now]);await connection.execute("UPDATE nodes SET status='AVAILABLE',current_task_id=NULL,resource_json=?,last_heartbeat=? WHERE id=?",[JSON.stringify(resources),now,nodeId]);});}
  async failOrRequeueNodeTasks(nodeId:string,error:string){await this.transaction(async connection=>{const timestamp=this.now();await connection.execute("UPDATE task_attempts a JOIN tasks t ON t.id=a.task_id AND t.attempt=a.attempt SET a.status='INTERRUPTED',a.completed_at=?,a.error=? WHERE a.node_id=? AND a.status IN ('ASSIGNED','RUNNING')",[timestamp,error,nodeId]);await connection.execute("UPDATE tasks SET status=IF(attempt>=3,'FAILED','REQUEUED'),error=?,assigned_node_id=NULL,completed_at=IF(attempt>=3,?,completed_at) WHERE assigned_node_id=? AND status IN ('ASSIGNED','RUNNING')",[error,timestamp,nodeId]);await connection.execute("UPDATE nodes SET current_task_id=NULL WHERE id=?",[nodeId]);});}
  async failTask(taskId:string,nodeId:string,attempt:number,error:string){return this.transaction(async connection=>{const timestamp=this.now();const[result]=await connection.execute<ResultSetHeader>("UPDATE tasks SET status=IF(attempt>=3,'FAILED','REQUEUED'),error=?,assigned_node_id=NULL,completed_at=IF(attempt>=3,?,completed_at) WHERE id=? AND assigned_node_id=? AND attempt=? AND status IN ('ASSIGNED','RUNNING')",[error,timestamp,taskId,nodeId,attempt]);if(result.affectedRows){const attemptStatus=error.includes("timed out")?"TIMED_OUT":"FAILED";await connection.execute("UPDATE task_attempts SET status=?,completed_at=?,error=? WHERE task_id=? AND attempt=? AND node_id=? AND status IN ('ASSIGNED','RUNNING')",[attemptStatus,timestamp,error,taskId,attempt,nodeId]);await connection.execute("UPDATE nodes SET status='AVAILABLE',current_task_id=NULL WHERE id=? AND status!='OFFLINE' AND revoked_at IS NULL",[nodeId]);}return result.affectedRows===1;});}
  private parseJson<T=unknown>(value:unknown):T{return(typeof value==="string"?JSON.parse(value):value) as T;}
}
