import mysql, { type Pool, type PoolConnection, type ResultSetHeader, type RowDataPacket } from "mysql2/promise";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { CapabilityProfile, NodeStatus, ResourceSnapshot, TaskStatus, TestTaskPayload, WorkPayload } from "@c-optiforge/contracts";
import type {CIntermediateRepresentation} from "@c-optiforge/compiler-c";

export type DatabaseConfig={host:string;port:number;name:string;user:string;password:string};
export type InvitationRecord={id:string;sessionId:string;status:string;expiresAt:string;acceptedAt:string|null;enrollmentHash:string|null;enrollmentExpiresAt:string|null;redeemedAt:string|null};

export class Store {
  private constructor(private readonly pool:Pool){}
  static async connect(config:DatabaseConfig){const pool=mysql.createPool({host:config.host,port:config.port,database:config.name,user:config.user,password:config.password,waitForConnections:true,connectionLimit:10,queueLimit:0,timezone:"Z",decimalNumbers:true});const store=new Store(pool);await store.migrate();return store;}
  async close(){await this.pool.end();}
  private async migrate(){const statements=[
    `CREATE TABLE IF NOT EXISTS sessions (id VARCHAR(64) PRIMARY KEY,status ENUM('ACTIVE','CLOSED','EXPIRED') NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32) NOT NULL,INDEX idx_sessions_status(status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS invitations (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,status ENUM('PENDING','ACCEPTED','DECLINED','REDEEMED','EXPIRED') NOT NULL,created_at VARCHAR(32) NOT NULL,expires_at VARCHAR(32) NOT NULL,accepted_at VARCHAR(32),enrollment_hash CHAR(64) UNIQUE,enrollment_expires_at VARCHAR(32),redeemed_at VARCHAR(32),CONSTRAINT fk_invitation_session FOREIGN KEY(session_id) REFERENCES sessions(id),INDEX idx_invitations_session(session_id,status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS nodes (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,invitation_id VARCHAR(64) NOT NULL UNIQUE,role ENUM('WORKER') NOT NULL,status ENUM('REGISTERING','ONLINE','AVAILABLE','BUSY','UNAVAILABLE','OFFLINE') NOT NULL,profile_json JSON NOT NULL,resource_json JSON,worker_token_hash CHAR(64) NOT NULL UNIQUE,registered_at VARCHAR(32) NOT NULL,last_heartbeat VARCHAR(32) NOT NULL,disconnected_at VARCHAR(32),current_task_id VARCHAR(64),CONSTRAINT fk_node_session FOREIGN KEY(session_id) REFERENCES sessions(id),CONSTRAINT fk_node_invitation FOREIGN KEY(invitation_id) REFERENCES invitations(id),INDEX idx_nodes_session_status(session_id,status),INDEX idx_nodes_heartbeat(last_heartbeat)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS tasks (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,kind VARCHAR(64) NOT NULL,payload_json JSON NOT NULL,required_capability VARCHAR(64) NOT NULL,status ENUM('QUEUED','ASSIGNED','RUNNING','COMPLETED','FAILED','REQUEUED') NOT NULL,assigned_node_id VARCHAR(64),attempt INT NOT NULL DEFAULT 0,created_at VARCHAR(32) NOT NULL,started_at VARCHAR(32),completed_at VARCHAR(32),error TEXT,CONSTRAINT fk_task_session FOREIGN KEY(session_id) REFERENCES sessions(id),CONSTRAINT fk_task_node FOREIGN KEY(assigned_node_id) REFERENCES nodes(id),INDEX idx_tasks_status(status,created_at)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS results (id VARCHAR(64) PRIMARY KEY,task_id VARCHAR(64) NOT NULL,node_id VARCHAR(64) NOT NULL,attempt INT NOT NULL,result_json JSON NOT NULL,execution_time_ms DOUBLE NOT NULL,resource_json JSON NOT NULL,created_at VARCHAR(32) NOT NULL,CONSTRAINT fk_result_task FOREIGN KEY(task_id) REFERENCES tasks(id),CONSTRAINT fk_result_node FOREIGN KEY(node_id) REFERENCES nodes(id),UNIQUE KEY uq_result_attempt(task_id,attempt)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS task_attempts (task_id VARCHAR(64) NOT NULL,attempt INT NOT NULL,node_id VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL,scheduler_score DOUBLE NOT NULL,scheduler_explanation TEXT NOT NULL,assigned_at VARCHAR(32) NOT NULL,started_at VARCHAR(32),completed_at VARCHAR(32),error TEXT,PRIMARY KEY(task_id,attempt),CONSTRAINT fk_attempt_task FOREIGN KEY(task_id) REFERENCES tasks(id),CONSTRAINT fk_attempt_node FOREIGN KEY(node_id) REFERENCES nodes(id),INDEX idx_attempt_node_status(node_id,status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS optimization_batches (id VARCHAR(64) PRIMARY KEY,session_id VARCHAR(64) NOT NULL,language VARCHAR(16) NOT NULL,status ENUM('DISTRIBUTING','COMPLETED','FAILED') NOT NULL,original_ir_json JSON NOT NULL,selected_ir_json JSON,evaluation_json JSON,created_at VARCHAR(32) NOT NULL,completed_at VARCHAR(32),CONSTRAINT fk_batch_session FOREIGN KEY(session_id) REFERENCES sessions(id),INDEX idx_batch_status(status)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS optimization_batch_tasks (batch_id VARCHAR(64) NOT NULL,task_id VARCHAR(64) NOT NULL,function_name VARCHAR(200) NOT NULL,PRIMARY KEY(batch_id,task_id),CONSTRAINT fk_batch_task_batch FOREIGN KEY(batch_id) REFERENCES optimization_batches(id),CONSTRAINT fk_batch_task_task FOREIGN KEY(task_id) REFERENCES tasks(id),UNIQUE KEY uq_batch_task(task_id)) ENGINE=InnoDB`
    ,`CREATE TABLE IF NOT EXISTS compilation_jobs (id VARCHAR(64) PRIMARY KEY,language ENUM('c','python','java') NOT NULL,source_name VARCHAR(255) NOT NULL,source_text MEDIUMTEXT NOT NULL,status ENUM('SUBMITTED','DISTRIBUTING','CODE_GENERATING','COMPLETED','FAILED') NOT NULL,stage VARCHAR(64) NOT NULL,batch_id VARCHAR(64),error TEXT,metrics_json JSON,created_at VARCHAR(32) NOT NULL,completed_at VARCHAR(32),CONSTRAINT fk_job_batch FOREIGN KEY(batch_id) REFERENCES optimization_batches(id),INDEX idx_jobs_status_created(status,created_at)) ENGINE=InnoDB`,
    `CREATE TABLE IF NOT EXISTS artifacts (id VARCHAR(64) PRIMARY KEY,job_id VARCHAR(64) NOT NULL UNIQUE,file_name VARCHAR(255) NOT NULL,media_type VARCHAR(150) NOT NULL,content LONGBLOB NOT NULL,size_bytes BIGINT NOT NULL,created_at VARCHAR(32) NOT NULL,CONSTRAINT fk_artifact_job FOREIGN KEY(job_id) REFERENCES compilation_jobs(id)) ENGINE=InnoDB`
  ];for(const sql of statements)await this.pool.execute(sql);await this.ensureColumn("tasks","scheduler_score","DOUBLE NULL");await this.ensureColumn("tasks","scheduler_explanation","TEXT NULL");await this.ensureColumn("tasks","job_id","VARCHAR(64) NULL");}
  private async ensureColumn(table:string,column:string,definition:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[table,column]);if(!rows.length)await this.pool.execute(`ALTER TABLE \`${table}\` ADD COLUMN \`${column}\` ${definition}`);}
  now(){return new Date().toISOString();} hash(token:string){return createHash("sha256").update(token).digest("hex");} token(){return randomBytes(32).toString("base64url");} id(prefix:string){return `${prefix}-${randomUUID()}`;}
  private async transaction<T>(work:(connection:PoolConnection)=>Promise<T>){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const result=await work(connection);await connection.commit();return result;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}

  async createSession(ttlMinutes=120){const id=this.id("SESSION"),createdAt=this.now(),expiresAt=new Date(Date.now()+ttlMinutes*60_000).toISOString(),rawToken=this.token(),invitationId=this.id("INVITE");await this.transaction(async connection=>{await connection.execute("INSERT INTO sessions(id,status,created_at,expires_at) VALUES(?,'ACTIVE',?,?)",[id,createdAt,expiresAt]);await connection.execute("INSERT INTO invitations(id,session_id,token_hash,status,created_at,expires_at) VALUES(?,?,?,'PENDING',?,?)",[invitationId,id,this.hash(rawToken),createdAt,expiresAt]);});return{id,status:"ACTIVE",createdAt,expiresAt,participationToken:rawToken};}
  async createInvitation(sessionId:string,ttlMinutes=120){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT status,expires_at expiresAt FROM sessions WHERE id=?",[sessionId]);const session=rows[0] as {status:string;expiresAt:string}|undefined;if(!session||session.status!=="ACTIVE"||Date.parse(session.expiresAt)<=Date.now())return undefined;const createdAt=this.now(),requestedExpiry=Date.now()+ttlMinutes*60_000,expiresAt=new Date(Math.min(requestedExpiry,Date.parse(session.expiresAt))).toISOString(),rawToken=this.token(),id=this.id("INVITE");await this.pool.execute("INSERT INTO invitations(id,session_id,token_hash,status,created_at,expires_at) VALUES(?,?,?,'PENDING',?,?)",[id,sessionId,this.hash(rawToken),createdAt,expiresAt]);return{id,sessionId,status:"PENDING",createdAt,expiresAt,participationToken:rawToken};}
  async getInvitation(rawToken:string):Promise<(InvitationRecord&{sessionStatus:string})|undefined>{const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT i.id,i.session_id sessionId,i.status,i.expires_at expiresAt,i.accepted_at acceptedAt,i.enrollment_hash enrollmentHash,i.enrollment_expires_at enrollmentExpiresAt,i.redeemed_at redeemedAt,s.status sessionStatus FROM invitations i JOIN sessions s ON s.id=i.session_id WHERE i.token_hash=?`,[this.hash(rawToken)]);return rows[0] as (InvitationRecord&{sessionStatus:string})|undefined;}
  async acceptInvitation(rawToken:string){const invitation=await this.getInvitation(rawToken);if(!invitation||invitation.status!=="PENDING"||invitation.sessionStatus!=="ACTIVE"||Date.parse(invitation.expiresAt)<=Date.now())return undefined;const enrollment=this.token(),now=this.now(),enrollmentExpiresAt=new Date(Date.now()+10*60_000).toISOString();const[result]=await this.pool.execute<ResultSetHeader>("UPDATE invitations SET status='ACCEPTED',accepted_at=?,enrollment_hash=?,enrollment_expires_at=? WHERE id=? AND status='PENDING'",[now,this.hash(enrollment),enrollmentExpiresAt,invitation.id]);return result.affectedRows===1?{enrollment,enrollmentExpiresAt,sessionId:invitation.sessionId}:undefined;}
  async declineInvitation(rawToken:string){const[result]=await this.pool.execute<ResultSetHeader>("UPDATE invitations SET status='DECLINED' WHERE token_hash=? AND status='PENDING'",[this.hash(rawToken)]);return result.affectedRows===1;}
  async redeemEnrollment(rawToken:string,profile:CapabilityProfile){return this.transaction(async connection=>{const[rows]=await connection.execute<RowDataPacket[]>(`SELECT i.id,i.session_id sessionId,i.status,i.enrollment_expires_at enrollmentExpiresAt,s.status sessionStatus FROM invitations i JOIN sessions s ON s.id=i.session_id WHERE i.enrollment_hash=? FOR UPDATE`,[this.hash(rawToken)]);const invitation=rows[0] as {id:string;sessionId:string;status:string;enrollmentExpiresAt:string;sessionStatus:string}|undefined;if(!invitation||invitation.status!=="ACCEPTED"||invitation.sessionStatus!=="ACTIVE"||Date.parse(invitation.enrollmentExpiresAt)<=Date.now())return undefined;const nodeId=this.id("NODE"),workerToken=this.token(),now=this.now();const[changed]=await connection.execute<ResultSetHeader>("UPDATE invitations SET status='REDEEMED',redeemed_at=? WHERE id=? AND status='ACCEPTED'",[now,invitation.id]);if(changed.affectedRows!==1)return undefined;await connection.execute(`INSERT INTO nodes(id,session_id,invitation_id,role,status,profile_json,worker_token_hash,registered_at,last_heartbeat) VALUES(?,?,?,'WORKER','ONLINE',?,?,?,?)`,[nodeId,invitation.sessionId,invitation.id,JSON.stringify(profile),this.hash(workerToken),now,now]);return{nodeId,workerToken,sessionId:invitation.sessionId};});}
  async authenticateWorker(rawToken:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,status FROM nodes WHERE worker_token_hash=?",[this.hash(rawToken)]);return rows[0] as {id:string;sessionId:string;status:NodeStatus}|undefined;}
  async reconnectWorker(nodeId:string){await this.pool.execute("UPDATE nodes SET status='ONLINE',disconnected_at=NULL,last_heartbeat=? WHERE id=?",[this.now(),nodeId]);}
  async heartbeat(nodeId:string,resources:ResourceSnapshot){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT status FROM nodes WHERE id=?",[nodeId]);const row=rows[0] as {status:NodeStatus}|undefined;if(!row||row.status==="OFFLINE")return false;const status=row.status==="ONLINE"||row.status==="UNAVAILABLE"?"AVAILABLE":row.status;await this.pool.execute("UPDATE nodes SET status=?,resource_json=?,last_heartbeat=?,disconnected_at=NULL WHERE id=?",[status,JSON.stringify(resources),this.now(),nodeId]);return true;}
  async markDisconnected(nodeId:string){await this.pool.execute("UPDATE nodes SET status='OFFLINE',disconnected_at=? WHERE id=? AND status!='OFFLINE'",[this.now(),nodeId]);}
  async recoverStaleNodes(staleBefore:string,offlineBefore:string){return this.transaction(async connection=>{const[rows]=await connection.execute<RowDataPacket[]>("SELECT id,status,last_heartbeat lastHeartbeat,current_task_id currentTaskId FROM nodes WHERE last_heartbeat<? AND status!='OFFLINE' FOR UPDATE",[staleBefore]);const recovered: Array<{nodeId:string;taskId:string|null;status:"UNAVAILABLE"|"OFFLINE"}> = [];for(const row of rows){const nodeId=String(row.id),taskId=row.currentTaskId?String(row.currentTaskId):null,status=Date.parse(String(row.lastHeartbeat))<Date.parse(offlineBefore)?"OFFLINE":"UNAVAILABLE",now=this.now(),reason=`Worker heartbeat lost; node marked ${status}`;if(taskId){const[taskRows]=await connection.execute<RowDataPacket[]>("SELECT attempt FROM tasks WHERE id=? FOR UPDATE",[taskId]);const attempt=Number(taskRows[0]?.attempt??0);await connection.execute("UPDATE task_attempts SET status='INTERRUPTED',completed_at=?,error=? WHERE task_id=? AND attempt=? AND status IN ('ASSIGNED','RUNNING')",[now,reason,taskId,attempt]);await connection.execute("UPDATE tasks SET status='REQUEUED',error=?,assigned_node_id=NULL WHERE id=? AND status IN ('ASSIGNED','RUNNING')",[reason,taskId]);}await connection.execute("UPDATE nodes SET status=?,current_task_id=NULL,disconnected_at=CASE WHEN ?='OFFLINE' THEN ? ELSE disconnected_at END WHERE id=?",[status,status,now,nodeId]);recovered.push({nodeId,taskId,status});}return recovered;});}
  async createTask(sessionId:string,payload:TestTaskPayload){return this.createWorkTask(sessionId,"TEST_COMPUTE",payload,"base");}
  async createWorkTask(sessionId:string,kind:"TEST_COMPUTE"|"C_OPTIMIZE_IR"|"PYTHON_COMPILE"|"JAVA_COMPILE",payload:WorkPayload,requiredCapability:"base"|"c"|"python"|"java"){const id=this.id("TASK"),now=this.now();await this.pool.execute("INSERT INTO tasks(id,session_id,kind,payload_json,required_capability,status,created_at) VALUES(?,?,?,?,?,'QUEUED',?)",[id,sessionId,kind,JSON.stringify(payload),requiredCapability,now]);return{id,sessionId,kind,payload,status:"QUEUED" as TaskStatus,attempt:0};}
  async createJobWorkTask(jobId:string,sessionId:string,kind:"PYTHON_COMPILE"|"JAVA_COMPILE",payload:WorkPayload,capability:"python"|"java"){const task=await this.createWorkTask(sessionId,kind,payload,capability);await this.pool.execute("UPDATE tasks SET job_id=? WHERE id=?",[jobId,task.id]);return task;}
  async getCompilationJobForTask(taskId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT job_id jobId FROM tasks WHERE id=?",[taskId]);return rows[0]?.jobId?this.getCompilationJob(String(rows[0].jobId)):undefined;}
  async createCOptimizationBatch(sessionId:string,ir:CIntermediateRepresentation){return this.transaction(async connection=>{const batchId=this.id("BATCH"),now=this.now(),tasks: Array<{taskId:string;functionName:string;status:"QUEUED"}> = [];await connection.execute("INSERT INTO optimization_batches(id,session_id,language,status,original_ir_json,created_at) VALUES(?,?,'c','DISTRIBUTING',?,?)",[batchId,sessionId,JSON.stringify(ir),now]);for(const fn of ir.functions){const taskId=this.id("TASK"),payload={operation:"c_optimize_ir" as const,function:fn};await connection.execute("INSERT INTO tasks(id,session_id,kind,payload_json,required_capability,status,created_at) VALUES(?,?,'C_OPTIMIZE_IR',?,'c','QUEUED',?)",[taskId,sessionId,JSON.stringify(payload),now]);await connection.execute("INSERT INTO optimization_batch_tasks(batch_id,task_id,function_name) VALUES(?,?,?)",[batchId,taskId,fn.name]);tasks.push({taskId,functionName:fn.name,status:"QUEUED"});}return{batchId,irKind:ir.kind,irVersion:ir.version,tasks};});}
  async getCOptimizationBatchForTask(taskId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT batch_id batchId FROM optimization_batch_tasks WHERE task_id=?",[taskId]);return rows[0]?this.getCOptimizationBatch(String(rows[0].batchId)):undefined;}
  async getCOptimizationBatch(batchId:string){const[[batchRows],[taskRows]]=await Promise.all([this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,status,original_ir_json originalIrJson,selected_ir_json selectedIrJson,evaluation_json evaluationJson,created_at createdAt,completed_at completedAt FROM optimization_batches WHERE id=?",[batchId]),this.pool.execute<RowDataPacket[]>(`SELECT bt.task_id taskId,bt.function_name functionName,t.status,t.assigned_node_id nodeId,t.attempt,r.result_json resultJson,r.execution_time_ms executionTimeMs FROM optimization_batch_tasks bt JOIN tasks t ON t.id=bt.task_id LEFT JOIN results r ON r.task_id=t.id AND r.attempt=t.attempt WHERE bt.batch_id=? ORDER BY bt.function_name`,[batchId])]);const row=batchRows[0];if(!row)return undefined;return{id:String(row.id),sessionId:String(row.sessionId),status:String(row.status),originalIR:this.parseJson<CIntermediateRepresentation>(row.originalIrJson),selectedIR:row.selectedIrJson?this.parseJson<CIntermediateRepresentation>(row.selectedIrJson):null,evaluation:row.evaluationJson?this.parseJson(row.evaluationJson):null,createdAt:String(row.createdAt),completedAt:row.completedAt?String(row.completedAt):null,tasks:taskRows.map(task=>({taskId:String(task.taskId),functionName:String(task.functionName),status:String(task.status),nodeId:task.nodeId?String(task.nodeId):null,attempt:Number(task.attempt),executionTimeMs:task.executionTimeMs===null?null:Number(task.executionTimeMs),result:task.resultJson?this.parseJson<any>(task.resultJson):null}))};}
  async completeCOptimizationBatch(batchId:string,selectedIR:CIntermediateRepresentation,evaluation:unknown){const[result]=await this.pool.execute<ResultSetHeader>("UPDATE optimization_batches SET status='COMPLETED',selected_ir_json=?,evaluation_json=?,completed_at=? WHERE id=? AND status='DISTRIBUTING'",[JSON.stringify(selectedIR),JSON.stringify(evaluation),this.now(),batchId]);return result.affectedRows===1;}
  async createCompilationJob(language:"c"|"python"|"java",sourceName:string,source:string){const id=this.id("JOB"),now=this.now();await this.pool.execute("INSERT INTO compilation_jobs(id,language,source_name,source_text,status,stage,created_at) VALUES(?,?,?,?,'SUBMITTED','VALIDATING',?)",[id,language,sourceName,source,now]);return{id,language,sourceName,status:"SUBMITTED",stage:"VALIDATING",createdAt:now};}
  async activeSession(){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id FROM sessions WHERE status='ACTIVE' AND expires_at>? ORDER BY created_at DESC LIMIT 1",[this.now()]);return rows[0]?String(rows[0].id):null;}
  async attachJobBatch(jobId:string,batchId:string){await this.pool.execute("UPDATE compilation_jobs SET status='DISTRIBUTING',stage='DISTRIBUTED_OPTIMIZATION',batch_id=? WHERE id=?",[batchId,jobId]);}
  async setJobStage(jobId:string,status:string,stage:string){await this.pool.execute("UPDATE compilation_jobs SET status=?,stage=? WHERE id=?",[status,stage,jobId]);}
  async completeCompilationJob(jobId:string,artifact:{fileName:string;mediaType:string;bytes:Buffer},metrics:unknown){await this.transaction(async connection=>{const artifactId=this.id("ARTIFACT"),now=this.now();await connection.execute("INSERT INTO artifacts(id,job_id,file_name,media_type,content,size_bytes,created_at) VALUES(?,?,?,?,?,?,?)",[artifactId,jobId,artifact.fileName,artifact.mediaType,artifact.bytes,artifact.bytes.byteLength,now]);await connection.execute("UPDATE compilation_jobs SET status='COMPLETED',stage='COMPLETED',metrics_json=?,completed_at=?,error=NULL WHERE id=?",[JSON.stringify(metrics),now,jobId]);});}
  async failCompilationJob(jobId:string,error:string){await this.pool.execute("UPDATE compilation_jobs SET status='FAILED',stage='FAILED',error=?,completed_at=? WHERE id=?",[error,this.now(),jobId]);}
  async getCompilationJob(jobId:string){const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT j.id,j.language,j.source_name sourceName,j.status,j.stage,j.batch_id batchId,j.error,j.metrics_json metricsJson,j.created_at createdAt,j.completed_at completedAt,a.id artifactId,a.file_name fileName,a.media_type mediaType,a.size_bytes sizeBytes FROM compilation_jobs j LEFT JOIN artifacts a ON a.job_id=j.id WHERE j.id=?`,[jobId]);const row=rows[0];return row?{id:String(row.id),language:String(row.language),sourceName:String(row.sourceName),status:String(row.status),stage:String(row.stage),batchId:row.batchId?String(row.batchId):null,error:row.error?String(row.error):null,metrics:row.metricsJson?this.parseJson(row.metricsJson):null,createdAt:String(row.createdAt),completedAt:row.completedAt?String(row.completedAt):null,artifact:row.artifactId?{id:String(row.artifactId),fileName:String(row.fileName),mediaType:String(row.mediaType),sizeBytes:Number(row.sizeBytes)}:null}:undefined;}
  async getCompilationJobByBatch(batchId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id FROM compilation_jobs WHERE batch_id=?",[batchId]);return rows[0]?this.getCompilationJob(String(rows[0].id)):undefined;}
  async getArtifact(artifactId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,job_id jobId,file_name fileName,media_type mediaType,content,size_bytes sizeBytes FROM artifacts WHERE id=?",[artifactId]);const row=rows[0];return row?{id:String(row.id),jobId:String(row.jobId),fileName:String(row.fileName),mediaType:String(row.mediaType),content:row.content as Buffer,sizeBytes:Number(row.sizeBytes)}:undefined;}
  async pendingTasks(){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,kind,payload_json payloadJson,required_capability requiredCapability,status,attempt FROM tasks WHERE status IN ('QUEUED','REQUEUED') ORDER BY created_at");return rows.map(row=>({id:String(row.id),sessionId:String(row.sessionId),kind:String(row.kind) as "TEST_COMPUTE"|"C_OPTIMIZE_IR"|"PYTHON_COMPILE"|"JAVA_COMPILE",payload:this.parseJson<WorkPayload>(row.payloadJson),requiredCapability:String(row.requiredCapability) as "base"|"c"|"python"|"java",status:row.status as TaskStatus,attempt:Number(row.attempt)}));}
  async getTask(taskId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,kind,payload_json payloadJson,status,assigned_node_id assignedNodeId,attempt FROM tasks WHERE id=?",[taskId]);const row=rows[0];return row?{...row,payload:this.parseJson(row.payloadJson),payloadJson:undefined}:undefined;}
  async availableNodes(sessionId:string){const[[rows],[historyRows]]=await Promise.all([this.pool.execute<RowDataPacket[]>("SELECT id,status,profile_json profileJson,resource_json resourceJson,last_heartbeat lastHeartbeat FROM nodes WHERE session_id=? AND status='AVAILABLE' AND current_task_id IS NULL",[sessionId]),this.pool.execute<RowDataPacket[]>(`SELECT a.node_id nodeId,t.required_capability capability,COUNT(*) sampleCount,AVG(r.execution_time_ms) averageExecutionTimeMs,AVG(a.status='COMPLETED') successRate FROM task_attempts a JOIN tasks t ON t.id=a.task_id LEFT JOIN results r ON r.task_id=a.task_id AND r.attempt=a.attempt WHERE t.session_id=? AND a.status IN ('COMPLETED','FAILED','TIMED_OUT','INTERRUPTED') GROUP BY a.node_id,t.required_capability`,[sessionId])]);const history=new Map<string,Record<string,unknown>>();for(const item of historyRows){if(item.averageExecutionTimeMs===null)continue;const record=history.get(String(item.nodeId))??{};record[String(item.capability)]={sampleCount:Number(item.sampleCount),averageExecutionTimeMs:Number(item.averageExecutionTimeMs),successRate:Number(item.successRate)};history.set(String(item.nodeId),record);}return rows.map(row=>({id:String(row.id),status:String(row.status),profile:this.parseJson<CapabilityProfile>(row.profileJson),resources:row.resourceJson?this.parseJson<ResourceSnapshot>(row.resourceJson):null,lastHeartbeat:String(row.lastHeartbeat),historicalPerformance:history.get(String(row.id))??{}}));}
  async assignTask(taskId:string,nodeId:string,score:number,explanation:string){return this.transaction(async connection=>{const[rows]=await connection.execute<RowDataPacket[]>("SELECT status,attempt FROM tasks WHERE id=? FOR UPDATE",[taskId]);const task=rows[0] as {status:TaskStatus;attempt:number}|undefined;if(!task||!["QUEUED","REQUEUED"].includes(task.status))throw new Error("Task is not assignable");const attempt=Number(task.attempt)+1,now=this.now();const[nodeChanged]=await connection.execute<ResultSetHeader>("UPDATE nodes SET status='BUSY',current_task_id=? WHERE id=? AND status='AVAILABLE' AND current_task_id IS NULL",[taskId,nodeId]);if(nodeChanged.affectedRows!==1)throw new Error("Node is not available");await connection.execute("UPDATE tasks SET status='ASSIGNED',assigned_node_id=?,attempt=?,scheduler_score=?,scheduler_explanation=?,error=NULL WHERE id=?",[nodeId,attempt,score,explanation,taskId]);await connection.execute("INSERT INTO task_attempts(task_id,attempt,node_id,status,scheduler_score,scheduler_explanation,assigned_at) VALUES(?,?,?,'ASSIGNED',?,?,?)",[taskId,attempt,nodeId,score,explanation,now]);return attempt;});}
  async setTaskRunning(taskId:string,nodeId:string,attempt:number){return this.transaction(async connection=>{const now=this.now();const[result]=await connection.execute<ResultSetHeader>("UPDATE tasks SET status='RUNNING',started_at=? WHERE id=? AND assigned_node_id=? AND attempt=? AND status='ASSIGNED'",[now,taskId,nodeId,attempt]);if(result.affectedRows===1)await connection.execute("UPDATE task_attempts SET status='RUNNING',started_at=? WHERE task_id=? AND attempt=? AND node_id=? AND status='ASSIGNED'",[now,taskId,attempt,nodeId]);return result.affectedRows===1;});}
  async completeTask(taskId:string,nodeId:string,attempt:number,result:unknown,executionTimeMs:number,resources:ResourceSnapshot){await this.transaction(async connection=>{const now=this.now();const[changed]=await connection.execute<ResultSetHeader>("UPDATE tasks SET status='COMPLETED',completed_at=? WHERE id=? AND assigned_node_id=? AND attempt=? AND status='RUNNING'",[now,taskId,nodeId,attempt]);if(changed.affectedRows!==1)throw new Error("Stale or invalid task result");await connection.execute("UPDATE task_attempts SET status='COMPLETED',completed_at=? WHERE task_id=? AND attempt=? AND node_id=? AND status='RUNNING'",[now,taskId,attempt,nodeId]);await connection.execute("INSERT INTO results(id,task_id,node_id,attempt,result_json,execution_time_ms,resource_json,created_at) VALUES(?,?,?,?,?,?,?,?)",[this.id("RESULT"),taskId,nodeId,attempt,JSON.stringify(result),executionTimeMs,JSON.stringify(resources),now]);await connection.execute("UPDATE nodes SET status='AVAILABLE',current_task_id=NULL,resource_json=?,last_heartbeat=? WHERE id=?",[JSON.stringify(resources),now,nodeId]);});}
  async failOrRequeueNodeTasks(nodeId:string,error:string){await this.transaction(async connection=>{const now=this.now();await connection.execute("UPDATE task_attempts a JOIN tasks t ON t.id=a.task_id AND t.attempt=a.attempt SET a.status='INTERRUPTED',a.completed_at=?,a.error=? WHERE a.node_id=? AND a.status IN ('ASSIGNED','RUNNING')",[now,error,nodeId]);await connection.execute("UPDATE tasks SET status='REQUEUED',error=?,assigned_node_id=NULL WHERE assigned_node_id=? AND status IN ('ASSIGNED','RUNNING')",[error,nodeId]);await connection.execute("UPDATE nodes SET current_task_id=NULL WHERE id=?",[nodeId]);});}
  async failTask(taskId:string,nodeId:string,attempt:number,error:string){return this.transaction(async connection=>{const[result]=await connection.execute<ResultSetHeader>("UPDATE tasks SET status='REQUEUED',error=?,assigned_node_id=NULL WHERE id=? AND assigned_node_id=? AND attempt=? AND status IN ('ASSIGNED','RUNNING')",[error,taskId,nodeId,attempt]);if(result.affectedRows){const status=error.includes("timed out")?"TIMED_OUT":"FAILED";await connection.execute("UPDATE task_attempts SET status=?,completed_at=?,error=? WHERE task_id=? AND attempt=? AND node_id=? AND status IN ('ASSIGNED','RUNNING')",[status,this.now(),error,taskId,attempt,nodeId]);await connection.execute("UPDATE nodes SET status='AVAILABLE',current_task_id=NULL WHERE id=? AND status!='OFFLINE'",[nodeId]);}return result.affectedRows===1;});}
  async snapshot(){const[[sessionRows],[nodeRows],[taskRows],[attemptRows]]=await Promise.all([this.pool.execute<RowDataPacket[]>("SELECT id,status,created_at createdAt,expires_at expiresAt FROM sessions ORDER BY created_at DESC LIMIT 1"),this.pool.execute<RowDataPacket[]>("SELECT id,session_id sessionId,status,profile_json profileJson,resource_json resourceJson,registered_at registeredAt,last_heartbeat lastHeartbeat,current_task_id currentTaskId FROM nodes ORDER BY registered_at DESC"),this.pool.execute<RowDataPacket[]>(`SELECT t.id,t.session_id sessionId,t.kind,t.payload_json payloadJson,t.status,t.assigned_node_id assignedNodeId,t.attempt,t.scheduler_score schedulerScore,t.scheduler_explanation schedulerExplanation,t.created_at createdAt,t.started_at startedAt,t.completed_at completedAt,t.error,r.result_json resultJson,r.execution_time_ms executionTimeMs FROM tasks t LEFT JOIN results r ON r.task_id=t.id AND r.attempt=t.attempt ORDER BY t.created_at DESC LIMIT 100`),this.pool.execute<RowDataPacket[]>("SELECT task_id taskId,attempt,node_id nodeId,status,scheduler_score schedulerScore,scheduler_explanation schedulerExplanation,assigned_at assignedAt,started_at startedAt,completed_at completedAt,error FROM task_attempts ORDER BY task_id,attempt")]);const attemptsByTask=new Map<string,RowDataPacket[]>();for(const attempt of attemptRows){const taskId=String(attempt.taskId),items=attemptsByTask.get(taskId)??[];items.push(attempt);attemptsByTask.set(taskId,items);}return{coordinator:{status:"ONLINE"},session:sessionRows[0],nodes:nodeRows.map(({profileJson,resourceJson,...row})=>({...row,profile:this.parseJson(profileJson),resources:resourceJson?this.parseJson(resourceJson):null})),tasks:taskRows.map(({payloadJson,resultJson,...row})=>({...row,payload:this.parseJson(payloadJson),result:resultJson?this.parseJson(resultJson):null,attempts:attemptsByTask.get(String(row.id))??[]}))};}
  private parseJson<T=unknown>(value:unknown):T{return(typeof value==="string"?JSON.parse(value):value) as T;}
}
