import {createHash,randomBytes,randomUUID} from "node:crypto";
import type {Pool,ResultSetHeader,RowDataPacket} from "mysql2/promise";
import type {CapabilityProfile,NodeStatus,ResourceSnapshot} from "@c-optiforge/contracts";

const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
const token=()=>randomBytes(32).toString("base64url");
const id=(prefix:string)=>`${prefix}-${randomUUID()}`;
const now=()=>new Date().toISOString();
const alphaCode=(value:number)=>{let code="",number=value;while(number>0){number--;code=String.fromCharCode(65+number%26)+code;number=Math.floor(number/26);}return code;};
export type Page={page:number;pageSize:number};

export class NetworkService{
  constructor(private readonly pool:Pool){}

  async create(input:{name:string;description:string;expiresAt:string|null;maxNodes:number},adminId:string){const networkId=id("NETWORK"),publicId=id("NET"),joinToken=token(),createdAt=now(),[countRows]=await this.pool.execute<RowDataPacket[]>("SELECT COUNT(*) total FROM distributed_networks"),networkCode=alphaCode(Number(countRows[0]?.total??0)+1);await this.pool.execute("INSERT INTO distributed_networks(id,public_id,join_token_hash,name,description,status,created_by,created_at,expires_at,max_nodes,configuration_json,network_code,next_node_number) VALUES(?,?,?,?,?,'ACTIVE',?,?,?,?,?,?,1)",[networkId,publicId,digest(joinToken),input.name,input.description,adminId,createdAt,input.expiresAt,input.maxNodes,JSON.stringify({}),networkCode]);return{id:networkId,publicId,networkCode,name:input.name,description:input.description,status:"ACTIVE",createdAt,expiresAt:input.expiresAt,maxNodes:input.maxNodes,joinToken};}
  async disable(networkId:string){const[result]=await this.pool.execute<ResultSetHeader>("UPDATE distributed_networks SET status='DISABLED' WHERE id=? AND status='ACTIVE'",[networkId]);if(!result.affectedRows)return false;const timestamp=now();await this.pool.execute("UPDATE network_enrollments SET status='REVOKED',consent_status='REVOKED',revoked_at=?,updated_at=? WHERE network_id=? AND status!='REVOKED'",[timestamp,timestamp,networkId]);await this.pool.execute("UPDATE nodes SET status='OFFLINE',revoked_at=?,current_task_id=NULL WHERE network_id=? AND revoked_at IS NULL",[timestamp,networkId]);return true;}

  async byJoinToken(raw:string){const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT n.id,n.public_id publicId,n.name,n.description,n.status,n.created_at createdAt,n.expires_at expiresAt,n.max_nodes maxNodes,(SELECT COUNT(*) FROM nodes w WHERE w.network_id=n.id AND w.revoked_at IS NULL) nodeCount FROM distributed_networks n WHERE n.join_token_hash=?`,[digest(raw)]);const row=rows[0];if(!row)return null;const expired=Boolean(row.expiresAt)&&Date.parse(String(row.expiresAt))<=Date.now();return{id:String(row.id),publicId:String(row.publicId),name:String(row.name),description:String(row.description),status:expired?"EXPIRED":String(row.status),createdAt:String(row.createdAt),expiresAt:row.expiresAt?String(row.expiresAt):null,maxNodes:Number(row.maxNodes),nodeCount:Number(row.nodeCount),accepting:String(row.status)==="ACTIVE"&&!expired&&Number(row.nodeCount)<Number(row.maxNodes)};}
  async isActive(networkId:string){const[rows]=await this.pool.execute<RowDataPacket[]>("SELECT id FROM distributed_networks WHERE id=? AND status='ACTIVE' AND (expires_at IS NULL OR expires_at>?)",[networkId,now()]);return Boolean(rows[0]);}

  async createEnrollment(rawJoinToken:string,workerType:"BROWSER"|"NATIVE",deviceIdentity:string){const network=await this.byJoinToken(rawJoinToken);if(!network?.accepting)return null;const enrollmentId=id("ENROLLMENT"),credential=token(),createdAt=now(),expiresAt=new Date(Date.now()+30*24*3_600_000).toISOString();await this.pool.execute("INSERT INTO network_enrollments(id,network_id,device_identity_hash,consent_status,status,worker_type,credential_hash,created_at,updated_at,expires_at) VALUES(?,?,?,'ACCEPTED','PENDING',?,?,?, ?,?)",[enrollmentId,network.id,digest(deviceIdentity),workerType,digest(credential),createdAt,createdAt,expiresAt]);return{enrollmentId,networkId:String(network.id),credential,expiresAt};}

  async authenticateCredential(raw:string){const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT e.id enrollmentId,e.network_id networkId,e.worker_type workerType,e.status,e.expires_at expiresAt,n.status networkStatus,n.expires_at networkExpiresAt,w.id nodeId,w.status nodeStatus FROM network_enrollments e JOIN distributed_networks n ON n.id=e.network_id LEFT JOIN nodes w ON w.enrollment_id=e.id WHERE e.credential_hash=? AND e.status IN ('PENDING','ACTIVE') AND e.revoked_at IS NULL`,[digest(raw)]);const row=rows[0];if(!row||row.networkStatus!=="ACTIVE"||(row.expiresAt&&Date.parse(String(row.expiresAt))<=Date.now())||(row.networkExpiresAt&&Date.parse(String(row.networkExpiresAt))<=Date.now()))return null;return{enrollmentId:String(row.enrollmentId),networkId:String(row.networkId),workerType:String(row.workerType) as "BROWSER"|"NATIVE",nodeId:row.nodeId?String(row.nodeId):null,nodeStatus:row.nodeStatus?String(row.nodeStatus) as NodeStatus:null};}

  async register(rawCredential:string,profile:CapabilityProfile){const auth=await this.authenticateCredential(rawCredential);if(!auth)return null;const connection=await this.pool.getConnection();try{await connection.beginTransaction();if(auth.nodeId){await connection.execute("UPDATE nodes SET status='ONLINE',profile_json=?,last_heartbeat=?,disconnected_at=NULL WHERE id=? AND revoked_at IS NULL",[JSON.stringify(profile),now(),auth.nodeId]);await connection.commit();return{nodeId:auth.nodeId,networkId:auth.networkId};}const[networkRows]=await connection.execute<RowDataPacket[]>("SELECT network_code networkCode,next_node_number nextNodeNumber FROM distributed_networks WHERE id=? AND status='ACTIVE' FOR UPDATE",[auth.networkId]);const network=networkRows[0];if(!network)throw new Error("Network is unavailable");const number=Number(network.nextNodeNumber),nodeId=`NODE-${String(network.networkCode)}${String(number).padStart(3,"0")}`,createdAt=now();await connection.execute("UPDATE distributed_networks SET next_node_number=? WHERE id=?",[number+1,auth.networkId]);await connection.execute("INSERT INTO nodes(id,session_id,invitation_id,role,status,profile_json,worker_token_hash,registered_at,last_heartbeat,network_id,enrollment_id,worker_type) VALUES(?,NULL,NULL,'WORKER','ONLINE',?,?,?, ?,?,?,?)",[nodeId,JSON.stringify(profile),digest(token()),createdAt,createdAt,auth.networkId,auth.enrollmentId,auth.workerType]);await connection.execute("UPDATE network_enrollments SET status='ACTIVE',updated_at=? WHERE id=?",[createdAt,auth.enrollmentId]);await connection.commit();return{nodeId,networkId:auth.networkId};}catch(error){await connection.rollback();throw error;}finally{connection.release();}}

  async leave(rawCredential:string){const auth=await this.authenticateCredential(rawCredential);if(!auth)return false;const changed=await this.revokeNode(auth.nodeId,auth.enrollmentId);return changed;}
  async revokeNode(nodeId:string|null,enrollmentId?:string){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const timestamp=now();if(nodeId)await connection.execute("UPDATE nodes SET status='OFFLINE',revoked_at=?,current_task_id=NULL WHERE id=?",[timestamp,nodeId]);const[result]=await connection.execute<ResultSetHeader>("UPDATE network_enrollments SET status='REVOKED',consent_status='REVOKED',revoked_at=?,updated_at=? WHERE id=COALESCE(?,(SELECT enrollment_id FROM nodes WHERE id=?)) AND status!='REVOKED'",[timestamp,timestamp,enrollmentId??null,nodeId]);await connection.commit();return result.affectedRows>0;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}

  async listNetworks(page:Page){const offset=(page.page-1)*page.pageSize;const[[items],[count]]=await Promise.all([this.pool.execute<RowDataPacket[]>(`SELECT n.id,n.public_id publicId,n.network_code networkCode,n.name,n.description,n.status,n.created_at createdAt,n.expires_at expiresAt,n.max_nodes maxNodes,COUNT(w.id) nodeCount,COALESCE(JSON_ARRAYAGG(IF(w.id IS NULL,NULL,JSON_OBJECT('id',w.id,'status',w.status,'workerType',w.worker_type,'lastHeartbeat',w.last_heartbeat))),JSON_ARRAY()) nodes FROM distributed_networks n LEFT JOIN nodes w ON w.network_id=n.id AND w.revoked_at IS NULL GROUP BY n.id ORDER BY n.created_at DESC LIMIT ? OFFSET ?`,[page.pageSize,offset]),this.pool.execute<RowDataPacket[]>("SELECT COUNT(*) total FROM distributed_networks")]);return this.page(items.map((item:any)=>({...item,nodes:(typeof item.nodes==="string"?JSON.parse(item.nodes):item.nodes).filter(Boolean)})),page,Number(count[0]?.total??0));}
  async listNodes(page:Page,networkId?:string){const offset=(page.page-1)*page.pageSize,where=networkId?"WHERE w.network_id=?":"",params=networkId?[networkId,page.pageSize,offset]:[page.pageSize,offset],countParams=networkId?[networkId]:[];const[[items],[count]]=await Promise.all([this.pool.execute<RowDataPacket[]>(`SELECT w.id,w.network_id networkId,n.name networkName,w.worker_type workerType,w.status,w.profile_json profileJson,w.resource_json resourceJson,w.registered_at registeredAt,w.last_heartbeat lastHeartbeat,w.current_task_id currentTaskId,w.revoked_at revokedAt,(SELECT COUNT(*) FROM task_attempts a WHERE a.node_id=w.id AND a.status='COMPLETED') tasksCompleted,(SELECT COUNT(*) FROM task_attempts a WHERE a.node_id=w.id AND a.status IN ('FAILED','TIMED_OUT','INTERRUPTED')) failures FROM nodes w JOIN distributed_networks n ON n.id=w.network_id ${where} ORDER BY w.registered_at DESC LIMIT ? OFFSET ?`,params),this.pool.execute<RowDataPacket[]>(`SELECT COUNT(*) total FROM nodes w ${where}`,countParams)]);return this.page(items.map(({profileJson,resourceJson,...row})=>({...row,profile:this.json(profileJson),resources:resourceJson?this.json(resourceJson):null})),page,Number(count[0]?.total??0));}
  async listTasks(page:Page,networkId?:string){const offset=(page.page-1)*page.pageSize,where=networkId?"WHERE t.network_id=?":"",params=networkId?[networkId,page.pageSize,offset]:[page.pageSize,offset],countParams=networkId?[networkId]:[];const[[items],[count]]=await Promise.all([this.pool.execute<RowDataPacket[]>(`SELECT t.id,t.network_id networkId,n.name networkName,t.kind,t.status,t.required_capability requiredCapability,t.assigned_node_id assignedNodeId,t.attempt,t.created_at createdAt,t.started_at startedAt,t.completed_at completedAt,t.error,(SELECT COUNT(*) FROM task_attempts a WHERE a.task_id=t.id) attemptCount FROM tasks t LEFT JOIN distributed_networks n ON n.id=t.network_id ${where} ORDER BY t.created_at DESC LIMIT ? OFFSET ?`,params),this.pool.execute<RowDataPacket[]>(`SELECT COUNT(*) total FROM tasks t ${where}`,countParams)]);return this.page(items,page,Number(count[0]?.total??0));}
  async taskDetails(taskId:string){const[taskRows]=await this.pool.execute<RowDataPacket[]>("SELECT id,network_id networkId,kind,status,required_capability requiredCapability,assigned_node_id assignedNodeId,attempt,created_at createdAt,started_at startedAt,completed_at completedAt,error FROM tasks WHERE id=?",[taskId]);if(!taskRows[0])return null;const[attempts]=await this.pool.execute<RowDataPacket[]>("SELECT attempt,node_id nodeId,status,scheduler_score schedulerScore,scheduler_explanation schedulerExplanation,assigned_at assignedAt,started_at startedAt,completed_at completedAt,error FROM task_attempts WHERE task_id=? ORDER BY attempt",[taskId]);return{...taskRows[0],attempts};}
  async listJobs(page:Page,userId?:string){const offset=(page.page-1)*page.pageSize,where=userId?"WHERE j.user_id=?":"",params=userId?[userId,page.pageSize,offset]:[page.pageSize,offset],countParams=userId?[userId]:[];const[[items],[count]]=await Promise.all([this.pool.execute<RowDataPacket[]>(`SELECT j.id,j.user_id userId,j.network_id networkId,n.name networkName,n.network_code networkCode,j.language,j.source_name sourceName,j.status,j.stage,j.error,j.created_at createdAt,j.completed_at completedAt,a.id artifactId,a.file_name fileName,a.size_bytes sizeBytes,(SELECT GROUP_CONCAT(DISTINCT ta.node_id ORDER BY ta.node_id SEPARATOR ',') FROM task_attempts ta JOIN tasks tx ON tx.id=ta.task_id WHERE tx.job_id=j.id OR tx.id IN (SELECT obt.task_id FROM optimization_batch_tasks obt WHERE obt.batch_id=j.batch_id)) participatingNodeIds FROM compilation_jobs j LEFT JOIN distributed_networks n ON n.id=j.network_id LEFT JOIN artifacts a ON a.job_id=j.id ${where} ORDER BY j.created_at DESC LIMIT ? OFFSET ?`,params),this.pool.execute<RowDataPacket[]>(`SELECT COUNT(*) total FROM compilation_jobs j ${where}`,countParams)]);return this.page(items.map((item:any)=>({...item,participatingNodes:item.participatingNodeIds?String(item.participatingNodeIds).split(","):[]})),page,Number(count[0]?.total??0));}
  private page(items:unknown[],page:Page,totalItems:number){return{items,page:page.page,pageSize:page.pageSize,totalItems,totalPages:Math.max(1,Math.ceil(totalItems/page.pageSize))};}
  private json(value:unknown){return typeof value==="string"?JSON.parse(value):value;}
}
