import Fastify from "fastify";
import cors from "@fastify/cors";
import websocket from "@fastify/websocket";
import type { WebSocket } from "ws";
import { z } from "zod";
import { parseWorkerMessage, testTaskSchema, type CoordinatorMessage } from "@c-optiforge/contracts";
import {selectNode} from "@c-optiforge/orchestration";
import { config } from "./config.js";
import { Store } from "./database.js";

const app=Fastify({logger:true,bodyLimit:200_000});
const store=await Store.connect(config.database);
const workers=new Map<string,WebSocket>();
const admins=new Set<WebSocket>();
let dispatching=false;

await app.register(cors,{origin:true});
await app.register(websocket,{options:{maxPayload:256_000}});

function send(socket:WebSocket,message:CoordinatorMessage|object){if(socket.readyState===socket.OPEN)socket.send(JSON.stringify(message));}
function adminAuthorized(request:{headers:Record<string,unknown>;query?:unknown}){const query=request.query as {key?:string}|undefined;return request.headers["x-admin-key"]===config.adminApiKey||query?.key===config.adminApiKey;}
function requireAdmin(request:any,reply:any,done:()=>void){if(!adminAuthorized(request)){reply.code(401).send({error:"ADMIN_AUTH_REQUIRED"});return;}done();}
async function broadcast(){const message=JSON.stringify({type:"snapshot",data:await store.snapshot()});for(const socket of admins)if(socket.readyState===socket.OPEN)socket.send(message);}
async function dispatchPending(){if(dispatching)return;dispatching=true;try{for(const task of await store.pendingTasks()){const connected=(await store.availableNodes(task.sessionId)).filter(node=>workers.has(node.id));const decision=selectNode(connected,{capability:task.requiredCapability,minLogicalCores:1,minFreeMemoryBytes:1_048_576});if(!decision.selectedNodeId||decision.score===null){app.log.info({event:"task_waiting_for_eligible_node",taskId:task.id,explanation:decision.explanation},"No eligible worker available");continue;}const chosenId=decision.selectedNodeId;try{const attempt=await store.assignTask(task.id,chosenId,decision.score,decision.explanation),socket=workers.get(chosenId)!;send(socket,{type:"task_assignment",taskId:task.id,attempt,taskKind:"TEST_COMPUTE",payload:task.payload});app.log.info({event:"task_assigned",taskId:task.id,nodeId:chosenId,attempt,score:decision.score,explanation:decision.explanation},"Task assigned by resource-aware scheduler");setTimeout(()=>void (async()=>{const current=await store.getTask(task.id) as any;if(current&&current.attempt===attempt&&["ASSIGNED","RUNNING"].includes(current.status)){await store.failTask(task.id,chosenId,attempt,"Task execution timed out");await broadcast();await dispatchPending();}})(),config.taskTimeoutMs).unref();}catch(error){app.log.warn({event:"assignment_race",taskId:task.id,nodeId:chosenId,error},"Assignment skipped");}}await broadcast();}finally{dispatching=false;}}

app.get("/health",async()=>({status:"ok",service:"c-optiforge-coordinator",database:"mysql",time:new Date().toISOString()}));
app.post("/api/admin/sessions",{preHandler:requireAdmin},async(request,reply)=>{const parsed=z.object({ttlMinutes:z.number().int().min(5).max(1440).default(120)}).safeParse(request.body??{});if(!parsed.success)return reply.code(400).send({error:"INVALID_REQUEST",details:parsed.error.issues});const session=await store.createSession(parsed.data.ttlMinutes),joinUrl=`${config.publicBaseUrl}/join/${session.participationToken}`;app.log.info({event:"session_created",sessionId:session.id},"Distributed session created");await broadcast();return{...session,participationToken:undefined,joinUrl};});
app.post("/api/admin/sessions/:sessionId/invitations",{preHandler:requireAdmin},async(request,reply)=>{const parsed=z.object({ttlMinutes:z.number().int().min(5).max(1440).default(120)}).safeParse(request.body??{});if(!parsed.success)return reply.code(400).send({error:"INVALID_REQUEST",details:parsed.error.issues});const{sessionId}=request.params as{sessionId:string},invitation=await store.createInvitation(sessionId,parsed.data.ttlMinutes);if(!invitation)return reply.code(409).send({error:"SESSION_NOT_ACTIVE"});const joinUrl=`${config.publicBaseUrl}/join/${invitation.participationToken}`;app.log.info({event:"invitation_created",sessionId},"Additional worker invitation created");await broadcast();return{...invitation,participationToken:undefined,joinUrl};});
app.get("/api/admin/snapshot",{preHandler:requireAdmin},async()=>store.snapshot());
app.post("/api/admin/tasks/test",{preHandler:requireAdmin},async(request,reply)=>{const parsed=z.object({sessionId:z.string(),payload:testTaskSchema}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"INVALID_TASK",details:parsed.error.issues});const task=await store.createTask(parsed.data.sessionId,parsed.data.payload);app.log.info({event:"task_created",taskId:task.id},"Test task created");void dispatchPending();return reply.code(201).send(task);});

app.get("/api/join/:token",async(request,reply)=>{const{token}=request.params as{token:string},invitation=await store.getInvitation(token);if(!invitation)return reply.code(404).send({error:"INVITATION_NOT_FOUND"});return{systemName:"C-OptiForge",sessionId:invitation.sessionId,status:invitation.status,expiresAt:invitation.expiresAt,disclosure:{purpose:"Contribute this device's computational resources to authorized compiler analysis and optimization tasks.",collects:["CPU model and logical core count","Operating system and architecture","Memory capacity and current utilization","C, Python, and Java toolchain availability","Task timing and resource measurements"],responsibilities:["Keep the worker agent running while participating","Execute only coordinator allow-listed workloads","Send periodic resource heartbeats"],implications:"The device may use CPU and memory while executing an assigned task. You may stop the worker agent at any time."}};});
app.post("/api/join/:token/accept",async(request,reply)=>{const{token}=request.params as{token:string},accepted=await store.acceptInvitation(token);if(!accepted)return reply.code(409).send({error:"INVITATION_NOT_ACCEPTABLE"});const forwardedProtocol=String(request.headers["x-forwarded-proto"]??request.protocol).split(",")[0]!.trim(),forwardedHost=String(request.headers["x-forwarded-host"]??request.headers.host??`localhost:${config.port}`).split(",")[0]!.trim(),coordinatorUrl=config.coordinatorPublicUrl??`${forwardedProtocol}://${forwardedHost}`;app.log.info({event:"invitation_accepted",sessionId:accepted.sessionId},"Worker participation accepted");return{sessionId:accepted.sessionId,enrollmentToken:accepted.enrollment,enrollmentExpiresAt:accepted.enrollmentExpiresAt,coordinatorUrl,command:`npm --prefix "${config.projectRoot}" run worker -- --coordinator ${coordinatorUrl} --enrollment ${accepted.enrollment}`};});
app.post("/api/join/:token/decline",async(request,reply)=>{const{token}=request.params as{token:string};return await store.declineInvitation(token)?reply.code(204).send():reply.code(409).send({error:"INVITATION_NOT_DECLINABLE"});});

app.get("/ws/admin",{websocket:true},(socket,request)=>{if(!adminAuthorized(request as any)){send(socket,{type:"error",code:"ADMIN_AUTH_REQUIRED",message:"Invalid admin key"});socket.close(1008);return;}admins.add(socket);void store.snapshot().then(data=>socket.send(JSON.stringify({type:"snapshot",data})));socket.on("close",()=>admins.delete(socket));});
app.get("/ws/worker",{websocket:true},(socket,request)=>{const query=request.query as{enrollment?:string;workerToken?:string};let nodeId:string|undefined,registered=false;let messageQueue=Promise.resolve();
  void(async()=>{if(query.workerToken){const node=await store.authenticateWorker(query.workerToken);if(node){nodeId=node.id;await store.reconnectWorker(nodeId);workers.set(nodeId,socket);registered=true;send(socket,{type:"registered",nodeId,workerToken:query.workerToken,heartbeatIntervalMs:5_000});await broadcast();}}})();
  socket.on("message",raw=>{messageQueue=messageQueue.then(async()=>{try{const message=parseWorkerMessage(JSON.parse(raw.toString()));if(message.type==="register"){if(registered||!query.enrollment)throw new Error("Registration is not allowed");const node=await store.redeemEnrollment(query.enrollment,message.profile);if(!node)throw new Error("Enrollment token is invalid, expired, or already used");nodeId=node.nodeId;registered=true;workers.set(nodeId,socket);send(socket,{type:"registered",nodeId,workerToken:node.workerToken,heartbeatIntervalMs:5_000});app.log.info({event:"node_registered",nodeId,sessionId:node.sessionId},"Worker registered");await broadcast();return;}if(!registered||!nodeId)throw new Error("Worker must register first");if(message.type==="heartbeat"){await store.heartbeat(nodeId,message.resources);await broadcast();await dispatchPending();}else if(message.type==="task_state"){if(message.status==="RUNNING")await store.setTaskRunning(message.taskId,nodeId,message.attempt);else await store.failTask(message.taskId,nodeId,message.attempt,message.error??"Worker reported failure");await broadcast();if(message.status==="FAILED")await dispatchPending();}else if(message.type==="task_result"){await store.completeTask(message.taskId,nodeId,message.attempt,message.result,message.executionTimeMs,message.resources);app.log.info({event:"task_completed",taskId:message.taskId,nodeId,attempt:message.attempt,executionTimeMs:message.executionTimeMs},"Worker task completed");await broadcast();await dispatchPending();}else if(message.type==="disconnect")socket.close(1000,"Worker leaving");}catch(error){app.log.warn({event:"worker_message_rejected",nodeId,error},"Rejected worker message");send(socket,{type:"error",code:"INVALID_MESSAGE",message:error instanceof Error?error.message:"Invalid message"});}});});
  socket.on("close",()=>void(async()=>{if(nodeId){workers.delete(nodeId);await store.failOrRequeueNodeTasks(nodeId,"Worker disconnected");await store.markDisconnected(nodeId);await broadcast();await dispatchPending();}})());});

setInterval(()=>void(async()=>{const now=Date.now(),recovered=await store.recoverStaleNodes(new Date(now-config.heartbeatStaleMs).toISOString(),new Date(now-config.heartbeatOfflineMs).toISOString());for(const item of recovered){const socket=workers.get(item.nodeId);workers.delete(item.nodeId);if(socket?.readyState===1)socket.close(1011,"Heartbeat timeout");app.log.warn({event:"worker_heartbeat_lost",...item},"Worker became unavailable");}if(recovered.length)await dispatchPending();await broadcast();})(),5_000).unref();
for(const signal of ["SIGINT","SIGTERM"] as const)process.once(signal,()=>void(async()=>{await app.close();await store.close();process.exit(0);})());
await app.listen({host:config.host,port:config.port});
