import Fastify,{type FastifyReply,type FastifyRequest} from "fastify";
import cors from "@fastify/cors";
import cookie from "@fastify/cookie";
import helmet from "@fastify/helmet";
import rateLimit from "@fastify/rate-limit";
import websocket from "@fastify/websocket";
import type {WebSocket} from "ws";
import {z} from "zod";
import {parseWorkerMessage,testTaskSchema,type CoordinatorMessage} from "@c-optiforge/contracts";
import {selectNode} from "@c-optiforge/orchestration";
import {aggregateCOptimization,compileCExecutable,lowerCToIR,type COptimizationCandidate} from "@c-optiforge/compiler-c";
import {config} from "./config.js";
import {Store,type StoredArtifact} from "./database.js";
import {buildReports} from "./build-report.js";
import {AuthService,passwordPolicy,type AuthUser,type Role} from "./auth.js";
import {NetworkService} from "./networks.js";

const SESSION_COOKIE="gridx_session",WORKER_COOKIE="gridx_worker",configuredOrigin=new URL(config.publicBaseUrl).origin;
const allowedOrigin=(value:string|undefined)=>{if(!value)return true;try{const url=new URL(value),host=url.hostname;return value===configuredOrigin||(url.protocol==="http:"&&(host==="localhost"||host==="127.0.0.1"||/^10\./.test(host)||/^192\.168\./.test(host)||/^172\.(1[6-9]|2\d|3[01])\./.test(host)));}catch{return false;}};
type AuthRequest=FastifyRequest&{auth?:AuthUser};
const apiError=(code:string,message:string,details?:unknown)=>({error:{code,message,...(details?{details}:{})}});

export async function buildServer(){
  const app=Fastify({logger:config.nodeEnv!=="test",bodyLimit:1_100_000,trustProxy:true}),store=await Store.connect(config.database),auth=new AuthService(store.pool,config.sessionTtlHours,config.resetTtlMinutes),networks=new NetworkService(store.pool);
  await auth.bootstrapAdmin(config.adminUsername,config.adminPasswordHash,config.adminPassword);
  await app.register(cookie);await app.register(helmet);await app.register(cors,{origin:(value,callback)=>callback(null,allowedOrigin(value)),credentials:true});await app.register(rateLimit,{global:false,max:100,timeWindow:"1 minute"});await app.register(websocket,{options:{maxPayload:1_100_000}});
  app.addHook("onRequest",async(request,reply)=>{if(["POST","PUT","PATCH","DELETE"].includes(request.method)&&!allowedOrigin(request.headers.origin))return reply.code(403).send(apiError("ORIGIN_REJECTED","The request origin is not allowed."));});
  app.setErrorHandler((cause:any,request,reply)=>{const status=Number(cause?.statusCode??500);if(status===429){request.log.warn({route:request.routeOptions.url},"request rate limited");return reply.code(429).send(apiError("RATE_LIMITED","Too many attempts. Wait a few minutes and try again."));}request.log.error({cause},"request failed");if(!reply.sent)reply.code(status>=400&&status<500?status:500).send(apiError(status>=400&&status<500?"REQUEST_REJECTED":"INTERNAL_ERROR",status>=400&&status<500?String(cause?.message??"The request was rejected."):"The request could not be completed."));});
  const currentUser=(request:AuthRequest)=>auth.session(request.cookies[SESSION_COOKIE]);
  const requireRole=(...roles:Role[])=>async(request:AuthRequest,reply:FastifyReply)=>{const user=await currentUser(request);if(!user)return reply.code(401).send(apiError("AUTH_REQUIRED","Sign in to continue."));if(!roles.includes(user.role))return reply.code(403).send(apiError("FORBIDDEN","You do not have permission for this action."));request.auth=user;};
  const requireAdmin=requireRole("ADMIN"),requireUser=requireRole("USER","ADMIN"),cookieOptions={httpOnly:true,sameSite:"strict" as const,secure:config.nodeEnv==="production",path:"/"};
  const pageSchema=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(10),networkId:z.string().optional()});
  const loginFailures=new Map<string,{count:number;windowStarted:number}>(),loginKey=(request:FastifyRequest,identifier:string)=>`${request.ip}:${identifier.trim().toLowerCase()}`;
  function loginRateLimited(key:string){const item=loginFailures.get(key);if(!item)return false;if(Date.now()-item.windowStarted>=15*60_000){loginFailures.delete(key);return false;}return item.count>=10;}
  function recordLoginFailure(key:string){const item=loginFailures.get(key),timestamp=Date.now();loginFailures.set(key,!item||timestamp-item.windowStarted>=15*60_000?{count:1,windowStarted:timestamp}:{...item,count:item.count+1});}

  app.get("/health",async()=>({status:"ok",service:"grid-x-coordinator",database:"mysql",time:new Date().toISOString()}));
  app.post("/api/auth/signup",{config:{rateLimit:{max:8,timeWindow:"15 minutes"}}},async(request,reply)=>{const parsed=z.object({name:z.string().trim().min(2).max(120),email:z.email().max(320),password:z.string().max(200),confirmPassword:z.string().max(200)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send(apiError("INVALID_SIGNUP","Check the registration fields.",parsed.error.issues));if(parsed.data.password!==parsed.data.confirmPassword)return reply.code(400).send(apiError("PASSWORD_MISMATCH","The passwords do not match."));if(!passwordPolicy(parsed.data.password))return reply.code(400).send(apiError("WEAK_PASSWORD","Use at least 12 characters with upper, lower, number, and symbol."));const user=await auth.signup(parsed.data.name,parsed.data.email,parsed.data.password);if(!user)return reply.code(409).send(apiError("EMAIL_EXISTS","An account already exists for this email."));await auth.audit("USER",user.id,"USER_CREATED","USER",user.id);return reply.code(201).send({user});});
  app.post("/api/auth/login",async(request,reply)=>{const parsed=z.object({identifier:z.string().trim().min(1).max(320),password:z.string().min(1).max(200)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send(apiError("INVALID_LOGIN","Enter your username/email and password."));const key=loginKey(request,parsed.data.identifier);if(loginRateLimited(key))return reply.code(429).send(apiError("RATE_LIMITED","Too many failed attempts. Wait a few minutes and try again."));const user=await auth.authenticate(parsed.data.identifier,parsed.data.password);if(!user){recordLoginFailure(key);await auth.audit("SYSTEM",null,"LOGIN_FAILED",null,null,{identifierHash:store.hash(parsed.data.identifier.toLowerCase())});return reply.code(401).send(apiError("INVALID_CREDENTIALS","The supplied credentials are invalid."));}loginFailures.delete(key);const session=await auth.createSession(user,request.ip,String(request.headers["user-agent"]??""));reply.setCookie(SESSION_COOKIE,session.token,{...cookieOptions,expires:new Date(session.expiresAt)});await auth.audit(user.role,user.id,"LOGIN_SUCCEEDED","USER",user.id);return{user,expiresAt:session.expiresAt};});
  app.get("/api/auth/me",async(request:AuthRequest,reply)=>{const user=await currentUser(request);return user?{user}:reply.code(401).send(apiError("AUTH_REQUIRED","Sign in to continue."));});
  app.post("/api/auth/logout",async(request:AuthRequest,reply)=>{const raw=request.cookies[SESSION_COOKIE],user=await currentUser(request);await auth.revokeSession(raw);reply.clearCookie(SESSION_COOKIE,cookieOptions);if(user)await auth.audit(user.role,user.id,"LOGOUT","USER",user.id);return reply.code(204).send();});
  app.post("/api/auth/forgot-password",{config:{rateLimit:{max:5,timeWindow:"15 minutes"}}},async(request,reply)=>{const parsed=z.object({email:z.email().max(320)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send(apiError("INVALID_EMAIL","Enter a valid email address."));const reset=await auth.createReset(parsed.data.email),response:{message:string;developmentResetUrl?:string}={message:"If the account exists, reset instructions are available."};if(reset&&config.nodeEnv!=="production")response.developmentResetUrl=`${config.publicBaseUrl}/reset-password?token=${encodeURIComponent(reset.token)}`;return response;});
  app.post("/api/auth/reset-password",{config:{rateLimit:{max:8,timeWindow:"15 minutes"}}},async(request,reply)=>{const parsed=z.object({token:z.string().min(20).max(200),password:z.string().max(200),confirmPassword:z.string().max(200)}).safeParse(request.body);if(!parsed.success||parsed.data.password!==parsed.data.confirmPassword||!passwordPolicy(parsed.data.password))return reply.code(400).send(apiError("INVALID_RESET","The reset token or password is invalid."));if(!await auth.resetPassword(parsed.data.token,parsed.data.password))return reply.code(410).send(apiError("RESET_EXPIRED","The reset link is invalid, expired, or already used."));return{message:"Password updated. Sign in with the new password."};});

  const admins=new Set<WebSocket>(),workers=new Map<string,WebSocket>(),unavailableSince=new Map<string,number>();let dispatching=false;
  const send=(socket:WebSocket,message:CoordinatorMessage|object)=>{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify(message));};
  const supportsConnected=(profile:{operations:{irOptimization:boolean};runtimes:{python:boolean;java:boolean}},capability:string)=>capability==="base"||capability==="ir"&&profile.operations.irOptimization||capability==="python"&&profile.runtimes.python||capability==="java"&&profile.runtimes.java;
  async function overview(){const[networkPage,nodes,tasks,jobs,[counts],[events]]=await Promise.all([networks.listNetworks({page:1,pageSize:10},true),networks.listNodes({page:1,pageSize:10}),networks.listTasks({page:1,pageSize:10}),networks.listJobs({page:1,pageSize:10}),store.pool.execute<any[]>(`SELECT (SELECT COUNT(*) FROM distributed_networks WHERE status='ACTIVE' AND (expires_at IS NULL OR expires_at>?)) activeNetworks,(SELECT COUNT(*) FROM nodes WHERE status IN ('ONLINE','AVAILABLE') AND revoked_at IS NULL) onlineWorkers,(SELECT COUNT(*) FROM nodes WHERE status='BUSY' AND revoked_at IS NULL) busyWorkers,(SELECT COUNT(*) FROM compilation_jobs WHERE status IN ('SUBMITTED','DISTRIBUTING','CODE_GENERATING')) activeJobs,(SELECT COUNT(*) FROM tasks WHERE status IN ('QUEUED','REQUEUED')) queuedTasks,(SELECT COUNT(*) FROM tasks WHERE status='FAILED') failedTasks`,[store.now()]),store.pool.execute<any[]>("SELECT id,event_type eventType,actor_type actorType,target_id targetId,created_at createdAt FROM audit_events ORDER BY created_at DESC LIMIT 8")]);return{coordinator:{status:"ONLINE"},summary:{networks:networkPage.totalItems,nodes:nodes.totalItems,tasks:tasks.totalItems,jobs:jobs.totalItems,...counts[0]},recentEvents:events,networks:networkPage,nodes,tasks,jobs};}
  async function broadcast(){const message=JSON.stringify({type:"snapshot",data:await overview()});for(const socket of admins)if(socket.readyState===socket.OPEN)socket.send(message);}
  async function dispatchPending(){if(dispatching)return;dispatching=true;try{for(const task of await store.pendingTasks()){const connected=(await store.availableNodes(task.networkId)).filter(node=>workers.has(node.id)),decision=selectNode(connected,{capability:task.requiredCapability,minLogicalCores:1,minFreeMemoryBytes:1_048_576});if(!decision.selectedNodeId||decision.score===null){const waiting=(await store.connectedNodes(task.networkId)).some(node=>workers.has(node.id)&&supportsConnected(node.profile,task.requiredCapability));if(waiting){unavailableSince.delete(task.id);continue;}const first=unavailableSince.get(task.id)??Date.now();unavailableSince.set(task.id,first);if(Date.now()-first>30_000){await store.failUnassignableTask(task.id,"No compatible worker remained available for this compilation.");unavailableSince.delete(task.id);}continue;}unavailableSince.delete(task.id);const nodeId=decision.selectedNodeId;try{const attempt=await store.assignTask(task.id,nodeId,decision.score,decision.explanation),socket=workers.get(nodeId)!;send(socket,{type:"task_assignment",taskId:task.id,attempt,taskKind:task.kind,payload:task.payload});await auth.audit("SYSTEM",null,"TASK_ASSIGNED","TASK",task.id,{nodeId,networkId:task.networkId,attempt});setTimeout(()=>void(async()=>{const current=await store.getTask(task.id) as any;if(current&&current.attempt===attempt&&["ASSIGNED","RUNNING"].includes(current.status)){await store.failTask(task.id,nodeId,attempt,"Task execution timed out");await store.reconcileFailedJobs();await broadcast();await dispatchPending();}})(),config.taskTimeoutMs).unref();}catch(cause){app.log.warn({cause,taskId:task.id,nodeId},"assignment skipped");}}await store.reconcileFailedJobs();await broadcast();}finally{dispatching=false;}}
  async function selectNetworkFor(capability:"ir"|"python"|"java"){const ranked=[] as Array<{networkId:string;score:number}>;for(let page=1;;page++){const networksPage=await networks.listNetworks({page,pageSize:100},true);for(const network of networksPage.items as any[]){const connected=(await store.availableNodes(network.id)).filter(node=>workers.has(node.id)),decision=selectNode(connected,{capability,minLogicalCores:1,minFreeMemoryBytes:1_048_576});if(decision.selectedNodeId&&decision.score!==null)ranked.push({networkId:network.id,score:decision.score});else if((await store.connectedNodes(network.id)).some(node=>workers.has(node.id)&&supportsConnected(node.profile,capability)))ranked.push({networkId:network.id,score:-1});}if(page>=networksPage.totalPages)break;}ranked.sort((a,b)=>b.score-a.score||a.networkId.localeCompare(b.networkId));return ranked[0]?.networkId??null;}
  async function finalizeJob(jobId:string,artifacts:StoredArtifact[],metrics:unknown,warnings:string[]=[]){const source=await store.getCompilationSource(jobId);if(!source)throw new Error("Compilation source is unavailable");await store.setJobStage(jobId,"CODE_GENERATING","ARTIFACT_GENERATION");const job=await store.getCompilationJob(jobId),processingTimeMs=job?Date.now()-Date.parse(job.createdAt):undefined;const reports=await buildReports({language:source.language,sourceName:source.sourceName,source:source.sourceText,artifacts,warnings,processingTimeMs});await store.completeCompilationJob(jobId,[...artifacts,...reports],metrics);}
  async function aggregateCompletedBatch(taskId:string){const batch=await store.getCOptimizationBatchForTask(taskId);if(!batch||batch.status!=="DISTRIBUTING"||batch.tasks.some(task=>task.status!=="COMPLETED"))return;const candidates=batch.tasks.map(task=>({taskId:task.taskId,nodeId:task.nodeId!,executionTimeMs:task.executionTimeMs!,function:task.result?.function,report:task.result?.report})).filter(candidate=>candidate.function) as COptimizationCandidate[],aggregated=aggregateCOptimization(batch.originalIR,candidates);if(await store.completeCOptimizationBatch(batch.id,aggregated.ir,aggregated)){const job=await store.getCompilationJobByBatch(batch.id);if(job)try{await store.setJobStage(job.id,"CODE_GENERATING","CODE_GENERATING");const source=await store.getCompilationSource(job.id);if(!source)throw new Error("Compilation source is unavailable");const base=source.sourceName.replace(/\.c$/i,"").replace(/[^A-Za-z0-9_-]/g,"_")||"program",artifact=await compileCExecutable(aggregated.ir,base),artifacts:StoredArtifact[]=[{artifactType:"GENERATED_SOURCE",fileName:source.sourceName,mediaType:"text/x-c; charset=utf-8",bytes:Buffer.from(artifact.generatedSource,"utf8")},{artifactType:"EXECUTABLE",fileName:artifact.fileName,mediaType:artifact.mediaType,bytes:artifact.bytes}];await finalizeJob(job.id,artifacts,{optimization:aggregated,compiler:artifact.compiler,artifactBytes:artifact.bytes.byteLength});}catch(cause){await store.failCompilationJob(job.id,cause instanceof Error?cause.message:"C code generation failed");}}}
  async function finalizeNativeJob(jobId:string,result:any,executionTimeMs:number){const source=await store.getCompilationSource(jobId);if(!source)throw new Error("Compilation source is unavailable");await store.setJobStage(jobId,"CODE_GENERATING","CODE_GENERATING");const original:StoredArtifact={artifactType:"SOURCE",fileName:source.sourceName,mediaType:source.language==="python"?"text/x-python; charset=utf-8":"text/x-java-source; charset=utf-8",bytes:Buffer.from(source.sourceText,"utf8")};let artifacts:StoredArtifact[];
    if(source.language==="python"){if(result.operation!=="python_compile"||typeof result.generatedSource!=="string"||typeof result.artifactBase64!=="string")throw new Error("Python worker returned incomplete compiler output");const optimizedName=`compiled_${source.sourceName}`;artifacts=[original,{artifactType:"GENERATED_SOURCE",fileName:optimizedName,mediaType:"text/x-python; charset=utf-8",bytes:Buffer.from(result.generatedSource,"utf8")},{artifactType:"BYTECODE",fileName:source.sourceName.replace(/\.py$/i,".pyc"),mediaType:"application/x-python-bytecode",bytes:Buffer.from(result.artifactBase64,"base64")}];}
    else if(source.language==="java"){if(result.operation!=="java_compile"||typeof result.artifactBase64!=="string"||!Array.isArray(result.classes)||!result.classes.length)throw new Error("Java worker returned incomplete compiler output");artifacts=[original,...result.classes.map((item:{fileName:string;contentBase64:string}):StoredArtifact=>({artifactType:"BYTECODE",fileName:item.fileName,mediaType:"application/java-vm",bytes:Buffer.from(item.contentBase64,"base64")})),{artifactType:"JAR",fileName:result.fileName,mediaType:"application/java-archive",bytes:Buffer.from(result.artifactBase64,"base64")}];}
    else throw new Error("Unexpected native compiler result");
    await finalizeJob(jobId,artifacts,{...result.metrics,workerExecutionTimeMs:executionTimeMs},Array.isArray(result.diagnostics)?result.diagnostics.filter((item:any)=>item.severity==="warning").map((item:any)=>String(item.message)):[]);
  }

  app.get("/api/admin/overview",{preHandler:requireAdmin},overview);
  app.get("/api/admin/networks",{preHandler:requireAdmin},async(request,reply)=>{const parsed=pageSchema.safeParse(request.query);return parsed.success?networks.listNetworks(parsed.data,true):reply.code(400).send(apiError("INVALID_PAGE","Invalid pagination parameters."));});
  app.post("/api/admin/networks",{preHandler:requireAdmin},async(request:AuthRequest,reply)=>{const parsed=z.object({name:z.string().trim().min(2).max(120),description:z.string().trim().max(1000).default(""),expiresAt:z.iso.datetime().nullable().default(null),maxNodes:z.number().int().min(1).max(1000).default(50)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send(apiError("INVALID_NETWORK","Check the network settings.",parsed.error.issues));const network=await networks.create(parsed.data,request.auth!.id);await auth.audit("ADMIN",request.auth!.id,"NETWORK_CREATED","NETWORK",network.id,{name:network.name});await broadcast();return reply.code(201).send({...network,joinToken:undefined,joinUrl:`${config.publicBaseUrl}/join/${network.joinToken}`});});
  app.post("/api/admin/networks/:networkId/disable",{preHandler:requireAdmin},async(request:AuthRequest,reply)=>{const{networkId}=request.params as{networkId:string};if(!await networks.disable(networkId))return reply.code(404).send(apiError("NETWORK_NOT_FOUND","The active network was not found."));for(const[nodeId,socket]of workers){const node=await store.pool.execute<any[]>("SELECT network_id networkId FROM nodes WHERE id=?",[nodeId]);if(node[0][0]?.networkId===networkId){socket.close(1008,"Network disabled");workers.delete(nodeId);}}await auth.audit("ADMIN",request.auth!.id,"NETWORK_DISABLED","NETWORK",networkId);await broadcast();return reply.code(204).send();});
  app.get("/api/admin/nodes",{preHandler:requireAdmin},async(request,reply)=>{const parsed=pageSchema.safeParse(request.query);return parsed.success?networks.listNodes(parsed.data,parsed.data.networkId):reply.code(400).send(apiError("INVALID_PAGE","Invalid pagination parameters."));});
  app.get("/api/admin/tasks",{preHandler:requireAdmin},async(request,reply)=>{const parsed=pageSchema.safeParse(request.query);return parsed.success?networks.listTasks(parsed.data,parsed.data.networkId):reply.code(400).send(apiError("INVALID_PAGE","Invalid pagination parameters."));});
  app.get("/api/admin/tasks/:taskId",{preHandler:requireAdmin},async(request,reply)=>{const{taskId}=request.params as{taskId:string},task=await networks.taskDetails(taskId);return task??reply.code(404).send(apiError("TASK_NOT_FOUND","The task was not found."));});
  app.get("/api/admin/jobs",{preHandler:requireAdmin},async(request,reply)=>{const parsed=pageSchema.safeParse(request.query);return parsed.success?networks.listJobs(parsed.data):reply.code(400).send(apiError("INVALID_PAGE","Invalid pagination parameters."));});
  app.post("/api/admin/nodes/:nodeId/revoke",{preHandler:requireAdmin},async(request:AuthRequest,reply)=>{const{nodeId}=request.params as{nodeId:string};if(!await networks.revokeNode(nodeId))return reply.code(404).send(apiError("NODE_NOT_FOUND","The worker node was not found."));workers.get(nodeId)?.close(1008,"Worker revoked");workers.delete(nodeId);await store.failOrRequeueNodeTasks(nodeId,"Worker revoked by administrator");await auth.audit("ADMIN",request.auth!.id,"NODE_REVOKED","NODE",nodeId);await broadcast();return reply.code(204).send();});
  app.post("/api/admin/tasks/test",{preHandler:requireAdmin},async(request,reply)=>{const parsed=z.object({networkId:z.string().min(1),payload:testTaskSchema}).safeParse(request.body);if(!parsed.success)return reply.code(400).send(apiError("INVALID_TASK","Check the task request.",parsed.error.issues));const taskId=store.id("TASK"),createdAt=store.now();await store.pool.execute("INSERT INTO tasks(id,session_id,network_id,kind,payload_json,required_capability,status,created_at) VALUES(?,NULL,?,'TEST_COMPUTE',?,'base','QUEUED',?)",[taskId,parsed.data.networkId,JSON.stringify(parsed.data.payload),createdAt]);void dispatchPending();return reply.code(201).send({id:taskId,status:"QUEUED"});});
  app.get("/api/admin/audit",{preHandler:requireAdmin},async(request,reply)=>{const parsed=pageSchema.safeParse(request.query);if(!parsed.success)return reply.code(400).send(apiError("INVALID_PAGE","Invalid pagination parameters."));const offset=(parsed.data.page-1)*parsed.data.pageSize,[rows]=await store.pool.execute<any[]>("SELECT id,actor_type actorType,actor_id actorId,event_type eventType,target_type targetType,target_id targetId,metadata_json metadata,created_at createdAt FROM audit_events ORDER BY created_at DESC LIMIT ? OFFSET ?",[parsed.data.pageSize,offset]),[count]=await store.pool.execute<any[]>("SELECT COUNT(*) total FROM audit_events");return{items:rows,page:parsed.data.page,pageSize:parsed.data.pageSize,totalItems:Number(count[0]?.total??0),totalPages:Math.max(1,Math.ceil(Number(count[0]?.total??0)/parsed.data.pageSize))};});

  app.get("/api/networks",{preHandler:requireUser},async()=>{const page=await networks.listNetworks({page:1,pageSize:100});return{items:page.items.filter((item:any)=>item.status==="ACTIVE")};});
  app.get("/api/jobs",{preHandler:requireUser},async(request:AuthRequest,reply)=>{const parsed=pageSchema.safeParse(request.query);return parsed.success?networks.listJobs(parsed.data,request.auth!.role==="ADMIN"?undefined:request.auth!.id):reply.code(400).send(apiError("INVALID_PAGE","Invalid pagination parameters."));});
  app.post("/api/compilations",{preHandler:requireRole("USER")},async(request:AuthRequest,reply)=>{
    const parsed=z.object({language:z.enum(["c","python","java"]),sourceName:z.string().min(1).max(255),source:z.string().min(1).max(1_000_000)}).safeParse(request.body);
    if(!parsed.success)return reply.code(400).send(apiError("INVALID_COMPILATION","Check the compilation request.",parsed.error.issues));
    const{language,sourceName,source}=parsed.data,extension={c:".c",python:".py",java:".java"}[language];
    if(!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(sourceName)||!sourceName.toLowerCase().endsWith(extension))return reply.code(400).send(apiError("INVALID_SOURCE_EXTENSION",`Use a filename ending in ${extension}, without a directory path.`));
    const javaPublicClass=language==="java"?source.match(/\bpublic\s+(?:final\s+)?class\s+([A-Za-z_$][\w$]*)/):null;
    if(javaPublicClass&&sourceName!==`${javaPublicClass[1]}.java`)return reply.code(400).send(apiError("INVALID_SOURCE_NAME",`A public Java class must use the filename ${javaPublicClass[1]}.java.`));
    const capability=language==="c"?"ir":language,networkId=await selectNetworkFor(capability);
    if(!networkId)return reply.code(409).send(apiError("NO_COMPATIBLE_NETWORK",language==="c"?"Connect an IR-capable browser or native worker to an active network.":"Connect a compatible native worker to an active network for this language."));
    const job=await store.createCompilationJob(request.auth!.id,networkId,language,sourceName,source);
    void(async()=>{try{if(language==="c"){const batch=await store.createCOptimizationBatch(networkId,lowerCToIR(source));await store.attachJobBatch(job.id,batch.batchId);}else{await store.setJobStage(job.id,"DISTRIBUTING","DISTRIBUTED_COMPILATION");await store.createJobWorkTask(job.id,networkId,language==="python"?"PYTHON_COMPILE":"JAVA_COMPILE",language==="python"?{operation:"python_compile",source}:{operation:"java_compile",source},language);}await dispatchPending();}catch(cause){await store.failCompilationJob(job.id,cause instanceof Error?cause.message:"Compilation failed");}finally{await broadcast();}})();
    return reply.code(202).send(job);
  });
  app.get("/api/compilations/:jobId",{preHandler:requireUser},async(request:AuthRequest,reply)=>{const{jobId}=request.params as{jobId:string},job=await store.getCompilationJob(jobId);if(!job||request.auth!.role!=="ADMIN"&&job.userId!==request.auth!.id)return reply.code(404).send(apiError("JOB_NOT_FOUND","The compilation job was not found."));return job;});
  app.get("/api/artifacts/:artifactId/download",{preHandler:requireUser},async(request:AuthRequest,reply)=>{const{artifactId}=request.params as{artifactId:string},artifact=await store.getArtifact(artifactId);if(!artifact)return reply.code(404).send(apiError("ARTIFACT_NOT_FOUND","The artifact was not found."));const job=await store.getCompilationJob(artifact.jobId);if(!job||job.status!=="COMPLETED"||request.auth!.role!=="ADMIN"&&job.userId!==request.auth!.id)return reply.code(404).send(apiError("ARTIFACT_NOT_FOUND","The artifact was not found."));return reply.header("Content-Type",artifact.mediaType).header("Content-Length",artifact.sizeBytes).header("Content-Disposition",`attachment; filename="${artifact.fileName.replace(/["\\]/g,"_")}"`).send(artifact.content);});

  app.get("/api/join/:token",async(request,reply)=>{const{token}=request.params as{token:string},network=await networks.byJoinToken(token);if(!network)return reply.code(404).send(apiError("NETWORK_NOT_FOUND","The distributed network is unavailable."));return{applicationName:"GRID-X",network};});
  app.post("/api/join/:token/accept",{config:{rateLimit:{max:12,timeWindow:"15 minutes"}}},async(request,reply)=>{const{token}=request.params as{token:string},parsed=z.object({workerType:z.enum(["BROWSER","NATIVE"]).default("BROWSER"),deviceIdentity:z.string().min(8).max(300)}).safeParse(request.body??{});if(!parsed.success)return reply.code(400).send(apiError("INVALID_ENROLLMENT","Device information is invalid."));const enrollment=await networks.createEnrollment(token,parsed.data.workerType,parsed.data.deviceIdentity);if(!enrollment)return reply.code(409).send(apiError("NETWORK_NOT_ACCEPTING","The network is disabled, expired, or full."));reply.setCookie(WORKER_COOKIE,enrollment.credential,{...cookieOptions,expires:new Date(enrollment.expiresAt)});await auth.audit("WORKER",enrollment.enrollmentId,"ENROLLMENT_ACCEPTED","NETWORK",enrollment.networkId,{workerType:parsed.data.workerType});return reply.code(201).send({enrollmentId:enrollment.enrollmentId,networkId:enrollment.networkId,workerType:parsed.data.workerType,expiresAt:enrollment.expiresAt,...(parsed.data.workerType==="NATIVE"&&config.nodeEnv!=="production"?{developmentNativeCredential:enrollment.credential}:{})});});
  app.post("/api/worker/leave",async(request,reply)=>{const credential=request.cookies[WORKER_COOKIE];if(!credential||!await networks.leave(credential))return reply.code(401).send(apiError("WORKER_AUTH_REQUIRED","The worker session is unavailable."));reply.clearCookie(WORKER_COOKIE,cookieOptions);return reply.code(204).send();});

  app.get("/ws/admin",{websocket:true},(socket,request)=>{void(async()=>{const user=await auth.session(request.cookies[SESSION_COOKIE]);if(user?.role!=="ADMIN"){socket.close(1008,"Authentication required");return;}admins.add(socket);send(socket,{type:"snapshot",data:await overview()});socket.on("close",()=>admins.delete(socket));})();});
  app.get("/ws/worker",{websocket:true},(socket,request)=>{const authorization=request.headers.authorization,credential=request.cookies[WORKER_COOKIE]??(authorization?.startsWith("Bearer ")?authorization.slice(7):undefined);let nodeId:string|undefined,networkId:string|undefined,registered=false,messageQueue=Promise.resolve();if(!credential){socket.close(1008,"Worker authentication required");return;}socket.on("message",raw=>{messageQueue=messageQueue.then(async()=>{try{const message=parseWorkerMessage(JSON.parse(raw.toString()));if(message.type==="register"){const node=await networks.register(credential,message.profile);if(!node)throw new Error("Worker credential is invalid, expired, or revoked");nodeId=node.nodeId;networkId=node.networkId;const prior=workers.get(nodeId);if(prior&&prior!==socket)prior.close(1012,"Reconnected elsewhere");workers.set(nodeId,socket);registered=true;send(socket,{type:"registered",nodeId,heartbeatIntervalMs:5_000});await auth.audit("WORKER",nodeId,"NODE_CONNECTED","NETWORK",networkId,{workerType:message.profile.workerType});await broadcast();return;}if(!registered||!nodeId)throw new Error("Worker must register first");if(message.type==="heartbeat"){await store.heartbeat(nodeId,message.resources);await broadcast();await dispatchPending();}else if(message.type==="task_state"){if(message.status==="RUNNING")await store.setTaskRunning(message.taskId,nodeId,message.attempt);else await store.failTask(message.taskId,nodeId,message.attempt,message.error??"Worker reported failure");await broadcast();if(message.status==="FAILED")await dispatchPending();}else if(message.type==="task_result"){await store.completeTask(message.taskId,nodeId,message.attempt,message.result,message.executionTimeMs,message.resources);await aggregateCompletedBatch(message.taskId);const job=await store.getCompilationJobForTask(message.taskId),result=message.result as any;if(job)try{await finalizeNativeJob(job.id,result,message.executionTimeMs);}catch(cause){await store.failCompilationJob(job.id,cause instanceof Error?cause.message:"Artifact generation failed");}await broadcast();await dispatchPending();}else if(message.type==="disconnect")socket.close(1000,"Worker leaving");}catch(cause){send(socket,{type:"error",code:"INVALID_MESSAGE",message:cause instanceof Error?cause.message:"Invalid message"});}});});socket.on("close",()=>void(async()=>{if(nodeId&&workers.get(nodeId)===socket){workers.delete(nodeId);await store.failOrRequeueNodeTasks(nodeId,"Worker disconnected");await store.markDisconnected(nodeId);await auth.audit("WORKER",nodeId,"WORKER_DISCONNECTED","NETWORK",networkId??null);await broadcast();await dispatchPending();}})());});
  setInterval(()=>void(async()=>{const timestamp=Date.now(),recovered=await store.recoverStaleNodes(new Date(timestamp-config.heartbeatStaleMs).toISOString(),new Date(timestamp-config.heartbeatOfflineMs).toISOString());for(const item of recovered){workers.get(item.nodeId)?.close(1011,"Heartbeat timeout");workers.delete(item.nodeId);}await dispatchPending();await store.reconcileFailedJobs();await broadcast();})(),5_000).unref();
  app.addHook("onClose",async()=>store.close());return app;
}

if(config.nodeEnv!=="test"){const app=await buildServer();for(const signal of ["SIGINT","SIGTERM"] as const)process.once(signal,()=>void app.close().then(()=>process.exit(0)));await app.listen({host:config.host,port:config.port});}
