import type {CIntermediateRepresentation,IRFunction,IRInstruction} from "./ir.js";
export type COptimizationCandidate={taskId:string;nodeId:string;executionTimeMs:number;function:IRFunction;report:unknown};
export type FunctionEvaluation={functionName:string;accepted:boolean;taskId:string|null;nodeId:string|null;originalCost:number;selectedCost:number;executionTimeMs:number|null;reason:string};
export type CAggregationResult={ir:CIntermediateRepresentation;evaluations:FunctionEvaluation[];totalWorkerTimeMs:number;acceptedCandidates:number};

export function aggregateCOptimization(original:CIntermediateRepresentation,candidates:COptimizationCandidate[]):CAggregationResult{
  const byName=new Map<string,COptimizationCandidate[]>();for(const candidate of candidates){const list=byName.get(candidate.function.name)??[];list.push(candidate);byName.set(candidate.function.name,list);}
  const evaluations:FunctionEvaluation[]=[],functions=original.functions.map(fn=>{const originalCost=cost(fn),eligible=(byName.get(fn.name)??[]).filter(candidate=>validCandidate(fn,candidate.function)).sort((a,b)=>cost(a.function)-cost(b.function)||a.executionTimeMs-b.executionTimeMs||a.taskId.localeCompare(b.taskId)),best=eligible[0];if(!best){evaluations.push({functionName:fn.name,accepted:false,taskId:null,nodeId:null,originalCost,selectedCost:originalCost,executionTimeMs:null,reason:"No structurally valid worker candidate; retained original IR."});return fn;}const selectedCost=cost(best.function);if(selectedCost>originalCost){evaluations.push({functionName:fn.name,accepted:false,taskId:best.taskId,nodeId:best.nodeId,originalCost,selectedCost:originalCost,executionTimeMs:best.executionTimeMs,reason:`Candidate cost ${selectedCost} exceeded original cost ${originalCost}; retained original IR.`});return fn;}evaluations.push({functionName:fn.name,accepted:true,taskId:best.taskId,nodeId:best.nodeId,originalCost,selectedCost,executionTimeMs:best.executionTimeMs,reason:`Accepted validated candidate with cost ${selectedCost} versus ${originalCost}.`});return best.function;});return{ir:{...original,functions},evaluations,totalWorkerTimeMs:evaluations.reduce((sum,item)=>sum+(item.executionTimeMs??0),0),acceptedCandidates:evaluations.filter(item=>item.accepted).length};
}
function cost(fn:IRFunction){return fn.instructions.reduce((sum,instruction)=>sum+(instruction.op==="call"?5:instruction.op==="branch"||instruction.op==="jump"?2:1),0);}
function validCandidate(original:IRFunction,candidate:IRFunction){if(candidate.name!==original.name||candidate.returnType!==original.returnType||candidate.parameters.length!==original.parameters.length||candidate.parameters.some((p,i)=>p.type!==original.parameters[i]!.type||p.value!==original.parameters[i]!.value))return false;if(candidate.instructions.length>original.instructions.length*2+16)return false;const labels=new Set(candidate.instructions.filter((i):i is Extract<IRInstruction,{op:"label"}>=>i.op==="label").map(i=>i.name));return candidate.instructions.every(instruction=>instruction.op==="jump"?labels.has(instruction.target):instruction.op==="branch"?labels.has(instruction.thenLabel)&&labels.has(instruction.elseLabel):true);}
