import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {spawn} from "node:child_process";
import type {CIntermediateRepresentation,IRFunction,IRInstruction} from "./ir.js";

export type CNativeArtifact={fileName:string;mediaType:string;bytes:Buffer;generatedSource:string;compiler:string;compilerOutput:string};
export function emitCFromIR(ir:CIntermediateRepresentation){if(ir.kind!=="COptiForgeCIR"||ir.version!==1)throw new Error("Unsupported C IR version");return ir.functions.map(emitFunction).join("\n\n")+"\n";}
function emitFunction(fn:IRFunction){const parameters=fn.parameters.map(p=>`${p.type} ${identifier(p.value)}`).join(", ")||"void",declared=new Set(fn.parameters.map(p=>p.value));for(const instruction of fn.instructions){const destination=dest(instruction);if(destination)declared.add(destination);}const locals=[...declared].filter(value=>!fn.parameters.some(p=>p.value===value)).map(value=>`  int ${identifier(value)} = 0;`),body=fn.instructions.map(emitInstruction);return`${fn.returnType} ${safeName(fn.name)}(${parameters}) {\n${[...locals,...body].join("\n")}\n}`;}
function emitInstruction(instruction:IRInstruction){switch(instruction.op){case"const":return`  ${identifier(instruction.dest)} = ${instruction.value};`;case"copy":return`  ${identifier(instruction.dest)} = ${identifier(instruction.source)};`;case"unary":return`  ${identifier(instruction.dest)} = ${instruction.operator}${identifier(instruction.operand)};`;case"binary":return`  ${identifier(instruction.dest)} = ${identifier(instruction.left)} ${instruction.operator} ${identifier(instruction.right)};`;case"call":{const call=`${safeName(instruction.callee)}(${instruction.arguments.map(identifier).join(", ")})`;return instruction.dest?`  ${identifier(instruction.dest)} = ${call};`:`  ${call};`;}case"label":return`${safeName(instruction.name)}:`;case"branch":return`  if (${identifier(instruction.condition)}) goto ${safeName(instruction.thenLabel)}; else goto ${safeName(instruction.elseLabel)};`;case"jump":return`  goto ${safeName(instruction.target)};`;case"return":return instruction.value?`  return ${identifier(instruction.value)};`:"  return;";}}
function dest(instruction:IRInstruction){return instruction.op==="const"||instruction.op==="copy"||instruction.op==="unary"||instruction.op==="binary"||instruction.op==="call"?instruction.dest:null;}
function identifier(value:string){return`v_${value.replace(/[^A-Za-z0-9_]/g,"_")}`;}
function safeName(value:string){const name=value.replace(/[^A-Za-z0-9_]/g,"_");return /^[A-Za-z_]/.test(name)?name:`f_${name}`;}
export async function compileCExecutable(ir:CIntermediateRepresentation,artifactName="program"):Promise<CNativeArtifact>{const workspace=await mkdtemp(join(tmpdir(),"c-optiforge-c-")),source=emitCFromIR(ir),sourcePath=join(workspace,"program.c"),fileName=process.platform==="win32"?`${artifactName}.exe`:artifactName,outputPath=join(workspace,fileName);try{await writeFile(sourcePath,source,"utf8");const version=await command("gcc",["--version"]);if(version.code!==0)throw new Error(`GCC is unavailable: ${version.stderr||version.stdout}`);const compiled=await command("gcc",["-std=c11","-O0","-Wall","-Werror",sourcePath,"-o",outputPath]);if(compiled.code!==0)throw new Error(`Native C code generation failed:\n${compiled.stderr||compiled.stdout}`);return{fileName,mediaType:process.platform==="win32"?"application/vnd.microsoft.portable-executable":"application/x-executable",bytes:await readFile(outputPath),generatedSource:source,compiler:version.stdout.split(/\r?\n/)[0]??"gcc",compilerOutput:[compiled.stdout,compiled.stderr].filter(Boolean).join("\n")};}finally{await rm(workspace,{recursive:true,force:true});}}
function command(executable:string,args:string[]){return new Promise<{code:number;stdout:string;stderr:string}>((resolve,reject)=>{const child=spawn(executable,args,{windowsHide:true}),stdout:Buffer[]=[],stderr:Buffer[]=[];let settled=false,outputBytes=0;const finish=(error?:Error,code=-1)=>{if(settled)return;settled=true;clearTimeout(timer);if(error)reject(error);else resolve({code,stdout:Buffer.concat(stdout).toString("utf8"),stderr:Buffer.concat(stderr).toString("utf8")});};const capture=(target:Buffer[])=>(chunk:Buffer)=>{outputBytes+=chunk.byteLength;if(outputBytes>8_000_000){child.kill();finish(new Error("C compiler output exceeded 8 MB"));return;}target.push(chunk);};const timer=setTimeout(()=>{child.kill();finish(new Error("C compiler timed out after 30 seconds"));},30_000);child.stdout.on("data",capture(stdout));child.stderr.on("data",capture(stderr));child.on("error",error=>finish(error));child.on("close",code=>finish(undefined,code??-1));});}
