import type {CIntermediateRepresentation,IRFunction,IRInstruction,IRValue} from "./ir.js";
export type OptimizationReport={constantFolds:number;algebraicSimplifications:number;deadInstructionsRemoved:number};
export function optimizeCIR(input:CIntermediateRepresentation):{ir:CIntermediateRepresentation;report:OptimizationReport}{const report:OptimizationReport={constantFolds:0,algebraicSimplifications:0,deadInstructionsRemoved:0};const functions=input.functions.map(fn=>optimizeFunction(fn,report));return{ir:{...input,functions},report};}
function optimizeFunction(fn:IRFunction,report:OptimizationReport):IRFunction{const constants=new Map<IRValue,number>(),instructions:IRInstruction[]=[];for(const instruction of fn.instructions){if(instruction.op==="label"||instruction.op==="branch"||instruction.op==="jump")constants.clear();if(instruction.op==="const"){constants.set(instruction.dest,instruction.value);instructions.push({...instruction});continue;}if(instruction.op==="copy"){const value=constants.get(instruction.source);if(value!==undefined){constants.set(instruction.dest,value);instructions.push({op:"const",dest:instruction.dest,value});report.constantFolds++;}else{constants.delete(instruction.dest);instructions.push({...instruction});}continue;}if(instruction.op==="unary"){const value=constants.get(instruction.operand);if(value!==undefined){const folded=instruction.operator==="+"?value:instruction.operator==="-"?-value:value===0?1:0;constants.set(instruction.dest,folded);instructions.push({op:"const",dest:instruction.dest,value:folded});report.constantFolds++;}else{constants.delete(instruction.dest);instructions.push({...instruction});}continue;}if(instruction.op==="binary"){const left=constants.get(instruction.left),right=constants.get(instruction.right);if(left!==undefined&&right!==undefined){const folded=evaluate(instruction.operator,left,right);if(folded!==undefined){constants.set(instruction.dest,folded);instructions.push({op:"const",dest:instruction.dest,value:folded});report.constantFolds++;continue;}}const replacement=simplify(instruction,left,right);if(replacement){constants.delete(instruction.dest);instructions.push(replacement);report.algebraicSimplifications++;}else{constants.delete(instruction.dest);instructions.push({...instruction});}continue;}if(instruction.op==="call"&&instruction.dest)constants.delete(instruction.dest);instructions.push({...instruction});}const live=new Set<IRValue>(),kept:IRInstruction[]=[];for(let index=instructions.length-1;index>=0;index--){const instruction=instructions[index]!;const destination=dest(instruction),removable=destination?.startsWith("%t")&&isPure(instruction)&&!live.has(destination);if(removable){report.deadInstructionsRemoved++;continue;}if(destination)live.delete(destination);for(const operand of operands(instruction))live.add(operand);kept.push(instruction);}kept.reverse();return{...fn,instructions:kept};}
function evaluate(operator:string,left:number,right:number){switch(operator){case"+":return left+right;case"-":return left-right;case"*":return left*right;case"/":return right===0?undefined:Math.trunc(left/right);case"%":return right===0?undefined:left%right;case"==":return Number(left===right);case"!=":return Number(left!==right);case"<":return Number(left<right);case"<=":return Number(left<=right);case">":return Number(left>right);case">=":return Number(left>=right);case"&&":return Number(left!==0&&right!==0);case"||":return Number(left!==0||right!==0);default:return undefined;}}
function simplify(instruction:Extract<IRInstruction,{op:"binary"}>,left:number|undefined,right:number|undefined):IRInstruction|undefined{if((instruction.operator==="+"&&right===0)||(instruction.operator==="-"&&right===0)||(instruction.operator==="*"&&right===1)||(instruction.operator==="/"&&right===1))return{op:"copy",dest:instruction.dest,source:instruction.left};if((instruction.operator==="+"&&left===0)||(instruction.operator==="*"&&left===1))return{op:"copy",dest:instruction.dest,source:instruction.right};return undefined;}
function dest(i:IRInstruction){return i.op==="const"||i.op==="copy"||i.op==="unary"||i.op==="binary"||i.op==="call"?i.dest??undefined:undefined;}
function isPure(i:IRInstruction){return i.op==="const"||i.op==="copy"||i.op==="unary"||i.op==="binary";}
function operands(i:IRInstruction):IRValue[]{switch(i.op){case"copy":return[i.source];case"unary":return[i.operand];case"binary":return[i.left,i.right];case"call":return i.arguments;case"branch":return[i.condition];case"return":return i.value?[i.value]:[];default:return[];}}
