import {lex,type SourceSpan,type Token,type TokenKind} from "./lexer.js";
import type {BlockStatement,CType,Expression,FunctionDefinition,Parameter,Program,Statement} from "./ast.js";

export class CParseError extends SyntaxError{constructor(message:string,readonly span:SourceSpan){super(`${message} at ${span.start.line}:${span.start.column}`);this.name="CParseError";}}
const binaryPrecedence:Partial<Record<TokenKind,number>>={"||":1,"&&":2,"==":3,"!=":3,"<":4,"<=":4,">":4,">=":4,"+":5,"-":5,"*":6,"/":6,"%":6};

export function parse(source:string):Program{return new Parser(lex(source)).program();}
class Parser{
  private current=0;constructor(private readonly tokens:Token[]){}
  private peek(offset=0){return this.tokens[Math.min(this.current+offset,this.tokens.length-1)]!;}
  private match(...kinds:TokenKind[]){if(kinds.includes(this.peek().kind)){return this.tokens[this.current++]!;}return undefined;}
  private expect(kind:TokenKind,message=`Expected '${kind}'`){const token=this.match(kind);if(!token)throw new CParseError(message,this.peek().span);return token;}
  private type():{type:CType;token:Token}{const token=this.match("int","void");if(!token)throw new CParseError("Expected type specifier",this.peek().span);return{type:token.kind as CType,token};}
  program():Program{const start=this.peek().span.start,functions:FunctionDefinition[]=[];while(this.peek().kind!=="eof")functions.push(this.functionDefinition());return{kind:"Program",functions,span:{start,end:this.peek().span.end}};}
  private functionDefinition():FunctionDefinition{const declared=this.type(),name=this.expect("identifier","Expected function name"),parameters=this.parameters(),body=this.block();return{kind:"FunctionDefinition",name:name.lexeme,returnType:declared.type,parameters,body,span:{start:declared.token.span.start,end:body.span.end}};}
  private parameters(){this.expect("(");const result:Parameter[]=[];if(this.match(")"))return result;if(this.peek().kind==="void"&&this.peek(1).kind===")"){this.current+=2;return result;}do{const declared=this.type();if(declared.type==="void")throw new CParseError("Named parameter cannot have void type",declared.token.span);const name=this.expect("identifier","Expected parameter name");result.push({kind:"Parameter",name:name.lexeme,type:declared.type,span:{start:declared.token.span.start,end:name.span.end}});}while(this.match(","));this.expect(")");return result;}
  private block():BlockStatement{const open=this.expect("{"),statements:Statement[]=[];while(this.peek().kind!=="}"&&this.peek().kind!=="eof")statements.push(this.statement());const close=this.expect("}","Expected '}' to close block");return{kind:"BlockStatement",statements,span:{start:open.span.start,end:close.span.end}};}
  private statement():Statement{if(this.peek().kind==="{")return this.block();if(this.peek().kind==="int"||this.peek().kind==="void")return this.declaration();const returned=this.match("return");if(returned){const expression=this.peek().kind===";"?null:this.expression();const end=this.expect(";");return{kind:"ReturnStatement",expression,span:{start:returned.span.start,end:end.span.end}};}const conditional=this.match("if");if(conditional){this.expect("(");const condition=this.expression();this.expect(")");const thenBranch=this.statement(),otherwise=this.match("else"),elseBranch=otherwise?this.statement():null;return{kind:"IfStatement",condition,thenBranch,elseBranch,span:{start:conditional.span.start,end:(elseBranch??thenBranch).span.end}};}const loop=this.match("while");if(loop){this.expect("(");const condition=this.expression();this.expect(")");const body=this.statement();return{kind:"WhileStatement",condition,body,span:{start:loop.span.start,end:body.span.end}};}const start=this.peek().span.start,expression=this.peek().kind===";"?null:this.expression(),end=this.expect(";");return{kind:"ExpressionStatement",expression,span:{start,end:end.span.end}};}
  private declaration():Statement{const declared=this.type();if(declared.type==="void")throw new CParseError("Variable cannot have void type",declared.token.span);const name=this.expect("identifier","Expected variable name"),initializer=this.match("=")?this.expression():null,end=this.expect(";");return{kind:"VariableDeclaration",name:name.lexeme,type:declared.type,initializer,span:{start:declared.token.span.start,end:end.span.end}};}
  private expression():Expression{return this.assignment();}
  private assignment():Expression{const left=this.binary(1);if(this.match("=")){if(left.kind!=="IdentifierExpression")throw new CParseError("Assignment target must be an identifier",left.span);const value=this.assignment();return{kind:"AssignmentExpression",target:left,value,span:{start:left.span.start,end:value.span.end}};}return left;}
  private binary(minimum:number):Expression{let left=this.unary();while(true){const operator=this.peek(),precedence=binaryPrecedence[operator.kind]??0;if(precedence<minimum)break;this.current++;const right=this.binary(precedence+1);left={kind:"BinaryExpression",operator:operator.kind as Extract<TokenKind,keyof typeof binaryPrecedence>,left,right,span:{start:left.span.start,end:right.span.end}} as Expression;}return left;}
  private unary():Expression{const operator=this.match("+","-","!");if(operator){const operand=this.unary();return{kind:"UnaryExpression",operator:operator.kind as "+"|"-"|"!",operand,span:{start:operator.span.start,end:operand.span.end}};}return this.primary();}
  private primary():Expression{const integer=this.match("integer");if(integer)return{kind:"IntegerLiteral",value:integer.value!,span:integer.span};const identifier=this.match("identifier");if(identifier){if(this.match("(")){const args:Expression[]=[];if(this.peek().kind!==")")do{args.push(this.expression());}while(this.match(","));const close=this.expect(")");return{kind:"CallExpression",callee:identifier.lexeme,arguments:args,span:{start:identifier.span.start,end:close.span.end}};}return{kind:"IdentifierExpression",name:identifier.lexeme,span:identifier.span};}const open=this.match("(");if(open){const expression=this.expression();this.expect(")");return expression;}throw new CParseError("Expected expression",this.peek().span);}
}
